#!/usr/bin/env python3
"""
Hermes — persistent orchestration agent for Jaiden's Mac Mini.
Listens for commands, spawns Claude Code sessions via tmux, reports back.
"""

import subprocess
import logging
import time
import threading
import yaml
import json
import shutil
import keyring
import requests
from datetime import datetime, timezone
from pathlib import Path
from typing import Callable, Optional

from planner import classify_task, PlannerResult
from run_engine import RunEngine
from agent_runner import AgentRunner, probe_models, apply_downgrade
from output_validator import validate_step_output
from project_registry import project_map_text, project_names, resolve as resolve_project
from scaffold_project import run_scaffold

CONFIG_PATH = Path.home() / "hermes" / "config" / "config.yaml"
STEP_MAX_RETRIES = 1  # max automatic retries per step (not applicable to rate-limited)
STEP_RETRY_DELAY_S = 10  # seconds to wait before retrying a failed step
LOG_PATH = Path.home() / "hermes" / "logs" / "hermes.log"

# Ensure logs directory exists before configuring file handler
LOG_PATH.parent.mkdir(parents=True, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.FileHandler(LOG_PATH), logging.StreamHandler()],
)
log = logging.getLogger("hermes")


def load_config():
    with open(CONFIG_PATH) as f:
        return yaml.safe_load(f)


def write_handoff_via_ollama(
    task: str,
    session_name: str,
    partial_output: str,
    cause: str = "Claude Code usage limit reached",
) -> str:
    """Use a local Ollama model to write a resume handoff for any failed step.

    `cause` is recorded in the note so the next agent knows why work stopped
    (rate-limit vs. validation failure vs. timeout) — the resume path differs.
    """
    log.info(f"Writing handoff via Ollama for: {session_name} (cause: {cause})")

    prompt = f"""You are writing a handoff note for an AI agent that could not finish its task.
Your job: read what was done and write a clear, actionable handoff so the next agent can resume without any human help.

ORIGINAL TASK:
{task}

PARTIAL OUTPUT (everything that ran before timeout):
{partial_output[:4000]}

Write a handoff note in this exact markdown format:

## What Was Completed
(bullet list of finished work — be specific, include file names and line numbers if mentioned)

## In Progress At Timeout
(what was being worked on when time ran out)

## Still Needs To Be Done
(remaining steps to fully complete the original task)

## How To Resume
(exact commands or steps the next agent should run first)

## Files Modified
(list any files that were changed, created, or deleted)

Be specific and factual. Only include what is supported by the partial output above."""

    try:
        import json as _json
        import urllib.request as _urllib

        payload = _json.dumps({"model": "llama3.1:8b", "prompt": prompt, "stream": False}).encode()
        req = _urllib.Request(
            "http://localhost:11434/api/generate",
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with _urllib.urlopen(req, timeout=120) as resp:
            response_text = _json.loads(resp.read().decode()).get("response", "").strip()

        if not response_text:
            log.error("Ollama handoff generation returned empty response")
            return ""

        handoff_dir = Path.home() / "Documents" / "RaphBrain" / "Projects" / "handoffs"
        handoff_dir.mkdir(parents=True, exist_ok=True)
        handoff_path = handoff_dir / f"{session_name}-handoff.md"
        handoff_path.write_text(
            f"# Auto-Handoff — {session_name}\n"
            f"*Generated by Ollama — cause: {cause}*\n"
            f"*{datetime.now().strftime('%Y-%m-%d %H:%M')}*\n\n"
            f"> **Original task:** {task[:200]}\n\n"
            f"{response_text}\n"
        )
        log.info(f"Handoff written: {handoff_path}")
        return str(handoff_path)
    except TimeoutError:
        log.error("Ollama handoff timed out after 120s")
        return ""
    except OSError:
        log.error("Ollama not found — is it installed?")
        return ""


# ---------------------------------------------------------------------------
# Handoff lifecycle — a failed step already writes a resume handoff; these let
# Jaiden actually work through them from the phone (list → resume → archive)
# instead of opening Jump Desktop. Canonical store is the flat handoffs/ dir;
# resolved ones move into handoffs/resolved/ so the pending list stays honest.
# ---------------------------------------------------------------------------
HANDOFFS_DIR = Path.home() / "Documents" / "RaphBrain" / "Projects" / "handoffs"
HANDOFFS_RESOLVED_DIR = HANDOFFS_DIR / "resolved"


def _pending_handoffs() -> list:
    """Unresolved handoff files, newest first. The top-level glob skips resolved/."""
    if not HANDOFFS_DIR.exists():
        return []
    files = [p for p in HANDOFFS_DIR.glob("*-handoff.md") if p.is_file()]
    return sorted(files, key=lambda p: p.stat().st_mtime, reverse=True)


def _parse_handoff_meta(text: str) -> dict:
    """Pull {project, task} from a handoff. project comes from the
    `<!-- hermes-meta project="X" -->` marker; task from the Original task line.
    Both best-effort — a legacy handoff with neither still lists, just can't
    auto-route (resume falls back to inferring the project)."""
    import re

    meta = {"project": "", "task": ""}
    m = re.search(r'hermes-meta[^>]*project="([^"]*)"', text)
    if m:
        meta["project"] = m.group(1)
    tm = re.search(r"original task:\**\s*(.+)", text, re.I)
    if tm:
        meta["task"] = tm.group(1).strip().rstrip("*").strip()
    return meta


def _list_handoffs() -> str:
    pend = _pending_handoffs()
    if not pend:
        return "✅ No pending handoffs."
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    lines = ["Pending handoffs — `resume <n>` to pick up, `handoffs clear` to dismiss all:"]
    for i, p in enumerate(pend, 1):
        try:
            meta = _parse_handoff_meta(p.read_text())
        except OSError:
            meta = {"project": "?", "task": "(unreadable)"}
        mtime = datetime.fromtimestamp(p.stat().st_mtime, timezone.utc).strftime(
            "%Y-%m-%dT%H:%M:%SZ"
        )
        lines.append(
            f"{i}. [{meta['project'] or '?'}] {(meta['task'] or '')[:48]} "
            f"— {_format_duration(mtime, now)} ago  ({p.stem})"
        )
    return "\n".join(lines)


def _clear_handoffs() -> str:
    pend = _pending_handoffs()
    if not pend:
        return "✅ No pending handoffs."
    HANDOFFS_RESOLVED_DIR.mkdir(parents=True, exist_ok=True)
    moved = 0
    for p in pend:
        try:
            p.rename(HANDOFFS_RESOLVED_DIR / p.name)
            moved += 1
        except OSError as exc:
            log.warning(f"[handoffs] could not archive {p.name}: {exc}")
    return f"🧹 Cleared {moved} handoff(s) → resolved/."


def _resume_handoff(arg: str, config: dict) -> str:
    """Resume a pending handoff: seed a fresh agent with it in the right repo,
    then archive the handoff (a new failure writes a fresh one, so the pending
    list always reflects reality). `arg` = an index into the pending list (empty →
    just list them), with an optional trailing project override (`2 alphabot`)."""
    pend = _pending_handoffs()
    if not pend:
        return "✅ No pending handoffs to resume. Send `handoffs` to check."

    parts = arg.split()
    sel = parts[0] if parts else ""
    override = parts[1] if len(parts) > 1 else ""

    if not sel:  # bare `resume` → just show the list to pick from
        return _list_handoffs()

    # A numeric selector is ONLY an index — an out-of-range number must fail, never
    # fall through to a substring match (stems embed unix timestamps full of digits,
    # so `resume 9` would silently match and resume the WRONG handoff).
    if sel.isdigit():
        i = int(sel)
        chosen = pend[i - 1] if 1 <= i <= len(pend) else None
    else:
        chosen = next((p for p in pend if sel in p.stem), None)
    if chosen is None:
        return f"❓ No pending handoff matches {sel!r}. Send `handoffs` to list them."

    try:
        text = chosen.read_text()
    except OSError as exc:
        return f"❓ Couldn't read handoff `{chosen.stem}`: {exc}"
    meta = _parse_handoff_meta(text)
    project = override or meta["project"]
    if not project and meta["task"]:
        try:
            project = classify_task(meta["task"]).project or ""
        except Exception:
            project = ""
    proj = resolve_project(project) if project else None
    if not proj or not proj.repo:
        guessed = f" (guessed {project!r})" if project else ""
        return (
            f"❓ Couldn't map handoff `{chosen.stem}` to a repo{guessed}.\n"
            f"Retry with a project: `resume {sel} <project>`."
        )

    resume_task = (
        "RESUME an unfinished task. A previous agent stopped partway and left the "
        "handoff below. Read it, pick up exactly where it left off, and finish the "
        "ORIGINAL TASK — do not restart from scratch.\n\n"
        f"ORIGINAL TASK: {meta['task'] or '(see handoff)'}\n\n"
        f"--- HANDOFF ---\n{text}"
    )
    ack = run_task(
        resume_task,
        on_complete=lambda r: _send_reply(config, r[:4096]),
        project=project,
        cwd=proj.repo,
    )
    try:
        HANDOFFS_RESOLVED_DIR.mkdir(parents=True, exist_ok=True)
        chosen.rename(HANDOFFS_RESOLVED_DIR / chosen.name)
    except OSError as exc:
        log.warning(f"[handoffs] archive-on-resume failed for {chosen.name}: {exc}")
    return f"▶ Resuming `{chosen.stem}` in {project}.\n{ack}"


# Hard safety kill for a direct task's agent subprocess. Real work finishes in
# minutes; this only backstops a hung/looping agent so it can't run forever.
# ponytail: single fixed ceiling — make it per-task config if tasks ever vary wildly.
DIRECT_SAFETY_TIMEOUT_S = 7200  # 2h

# Live direct tasks, so `status` can show them and `abort` can kill them.
# session_name -> {"task", "project", "started", "proc"}
_DIRECT_TASKS: dict = {}
_DIRECT_LOCK = threading.Lock()


def _resolve_claude_bin() -> str:
    """Absolute path to the claude CLI — a launchd daemon's PATH can be minimal."""
    return shutil.which("claude") or str(Path.home() / ".local" / "bin" / "claude")


def run_task(
    task: str,
    session_name: Optional[str] = None,
    on_complete: Optional[Callable[[str], None]] = None,
    project: Optional[str] = None,
    cwd: Optional[str] = None,
) -> str:
    """Run a direct task via `claude --print` in a background thread.

    Returns immediately with a short ack. When the agent process exits (or is
    killed after DIRECT_SAFETY_TIMEOUT_S) the captured output is handed to
    on_complete — so the daemon never blocks and a slow task is never falsely
    reported as timed out. `cwd` (a project repo) is where the agent runs;
    `project` is echoed in the ack so a wrong route is visible immediately.
    """
    if not session_name:
        session_name = f"hermes-{int(time.time())}"

    log.info(f"Spawning direct task: {session_name}")
    log.info(f"Task: {task[:120]}...")

    task_file = Path.home() / "hermes" / "tasks" / f"{session_name}.md"
    task_file.parent.mkdir(parents=True, exist_ok=True)
    task_file.write_text(f"# Hermes Task\n\n{task}\n")
    log_file = Path.home() / "hermes" / "logs" / f"{session_name}.log"
    log_file.parent.mkdir(parents=True, exist_ok=True)

    # Direct tasks default to sonnet — the classifier sometimes routes real work
    # here, and the cheapest model bounces on anything non-trivial.
    try:
        direct_cfg = load_config().get("models", {}).get("agent_models", {}).get("direct", {})
    except Exception:
        direct_cfg = {}
    direct_model = apply_downgrade(direct_cfg.get("model", "sonnet"))
    direct_max_turns = int(direct_cfg.get("max_turns", 30))

    cmd = [
        _resolve_claude_bin(),
        "--print",
        f"{project_map_text()}\n\n---\n\n{task}",
        "--model",
        str(direct_model),
        "--max-turns",
        str(direct_max_turns),
        # acceptEdits auto-approves file edits; --allowed-tools pre-approves the
        # read/inspect tools a phone status-check needs (ps, psql, git log, …) —
        # otherwise Bash is auto-denied in this headless run and "is X running?"
        # can't actually check anything.
        "--permission-mode",
        "acceptEdits",
        # Variadic — keep last so it collects all four tool names.
        "--allowed-tools",
        "Bash",
        "Read",
        "Grep",
        "Glob",
    ]

    run_cwd = str(Path(cwd).expanduser()) if cwd else str(Path.home())

    def _worker() -> None:
        result = ""
        try:
            proc = subprocess.Popen(
                cmd,
                cwd=run_cwd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
            )
            with _DIRECT_LOCK:
                _DIRECT_TASKS[session_name] = {
                    "task": task,
                    "project": project,
                    "started": time.time(),
                    "proc": proc,
                }
            try:
                out, _ = proc.communicate(timeout=DIRECT_SAFETY_TIMEOUT_S)
                result = out.strip() or "(agent produced no output)"
                if proc.returncode and proc.returncode < 0:  # killed by a signal (abort)
                    result = f"🛑 Aborted.\n{result}"
            except subprocess.TimeoutExpired:
                proc.kill()
                out, _ = proc.communicate()
                hrs = DIRECT_SAFETY_TIMEOUT_S // 3600
                log.warning(f"Direct task hard-killed after {hrs}h: {session_name}")
                result = f"{(out or '').strip()}\n\n⚠️ Killed after {hrs}h safety timeout."
            log_file.write_text(result)
            log.info(f"Direct task complete: {session_name}")
        except Exception as exc:
            log.error(f"Direct task {session_name} failed: {exc}", exc_info=True)
            result = f"❌ Task {session_name} failed: {exc}"
        finally:
            with _DIRECT_LOCK:
                _DIRECT_TASKS.pop(session_name, None)

        if on_complete:
            try:
                on_complete(result)
            except Exception as exc:
                log.error(f"on_complete callback failed for {session_name}: {exc}")
        else:
            log.info(f"Direct task {session_name} result (no callback): {result[:200]}")

    threading.Thread(target=_worker, daemon=True, name=f"hermes-task-{session_name}").start()
    tag = f" (project: {project})" if project else ""
    return f"▶ Started {session_name}{tag} — I'll send the result when it's done."


# ---------------------------------------------------------------------------
# Pipeline orchestration helpers
# ---------------------------------------------------------------------------

RAPHBRAIN_DAILY_DIR = Path.home() / "Documents" / "RaphBrain" / "Daily"


def _append_pipeline_to_daily_note(
    project: str,
    branch: str,
    final_status: str,
    duration: str,
    failed_step: str = "",
    reason: str = "",
) -> None:
    """Append a one-liner pipeline result to today's RaphBrain daily note."""
    try:
        today = datetime.now().strftime("%Y-%m-%d")
        daily_path = RAPHBRAIN_DAILY_DIR / f"{today}.md"

        if final_status == "done":
            line = f"\n- ✅ Hermes: `{project}/{branch}` done in {duration}"
        elif final_status == "failed":
            why = f" — {reason}" if reason else ""
            line = f"\n- ❌ Hermes: `{project}` failed at `{failed_step}`{why} ({duration})"
        elif final_status == "aborted":
            line = f"\n- 🛑 Hermes: `{project}/{branch}` aborted ({duration})"
        else:
            return  # don't log unknown states

        if daily_path.exists():
            with daily_path.open("a") as f:
                f.write(line)
        else:
            daily_path.parent.mkdir(parents=True, exist_ok=True)
            daily_path.write_text(f"# {today}\n{line}\n")

        log.info(f"[daily-note] Appended pipeline result to {daily_path.name}")
    except Exception as exc:
        log.warning(f"[daily-note] Failed to write to daily note: {exc}")


def _format_duration(started_iso: str, ended_iso: str) -> str:
    """Return a human-readable duration like '2m 14s'."""
    try:
        fmt = "%Y-%m-%dT%H:%M:%SZ"
        delta = int(
            (
                datetime.strptime(ended_iso, fmt) - datetime.strptime(started_iso, fmt)
            ).total_seconds()
        )
        if delta < 0:
            delta = 0
        mins, secs = divmod(delta, 60)
        return f"{mins}m {secs:02d}s" if mins else f"{secs}s"
    except Exception:
        return "??"


def _redact_token(text: str, token: Optional[str]) -> str:
    """Strip a bot token out of a string before it reaches the logs. requests
    exceptions embed the full request URL (…/bot<TOKEN>/…), so logging a raw exc
    leaks the token into hermes.log."""
    return text.replace(token, "***") if token else text


def _send_telegram(token: str, chat_id: int, message: str) -> None:
    """Send a message to a Telegram chat via Bot API."""
    try:
        resp = requests.post(
            f"https://api.telegram.org/bot{token}/sendMessage",
            json={"chat_id": chat_id, "text": message},
            timeout=10,
        )
        if not resp.ok:
            log.error(f"Telegram send failed: {_redact_token(resp.text, token)}")
        else:
            log.info(f"Telegram message sent to {chat_id}: {message[:80]}")
    except Exception as exc:
        log.error(f"Telegram send error: {_redact_token(str(exc), token)}")


def _send_reply(config: dict, message: str) -> None:
    """Send a reply over Telegram — the only supported channel."""
    tcfg = config["trigger"]["telegram"]
    token = keyring.get_password(
        tcfg["bot_token_keychain_service"], tcfg["bot_token_keychain_account"]
    )
    _send_telegram(token, tcfg["chat_id"], message)


def _run_pipeline(run_id: str, engine: RunEngine, runner: AgentRunner, hermes_config: dict) -> None:
    """
    Background thread: drives a full pipeline run to completion.

    For each step (or parallel group of steps):
      1. Call AgentRunner.dispatch_step() -> task_id  (non-blocking)
      2. Call engine.mark_step_started(run_id, idx, task_id)
      3. Call engine.poll_step_completion()  (blocks until done/failed/timeout)
      4. Call engine.mark_step_done() or engine.mark_step_failed()
      5. Send milestone notification

    Parallel groups are dispatched as sub-threads and joined before continuing.
    Completion/failure notification is sent when the last step resolves.
    """

    def _dispatch_one_step(run_id: str, idx: int, step: dict, run_snapshot: dict) -> None:
        """Dispatch a single step, poll to completion, update engine state."""
        role = step["role"]
        try:
            task_id = runner.dispatch_step(
                step=step,
                run=run_snapshot,
                task_description=run_snapshot["task_raw"],
            )
        except Exception as exc:
            log.error(f"[orchestrate] dispatch_step failed for role={role}: {exc}")
            engine.mark_step_failed(run_id, idx, reason=f"dispatch failed: {exc}")
            return

        engine.mark_step_started(run_id, idx, task_id)
        log.info(f"[orchestrate] Step {idx} ({role}) dispatched as task {task_id}")

        def _finalize_step_failure(reason: str) -> None:
            """Terminal failure for this step: mark it failed, write a resume
            handoff from whatever partial output exists, and text Jaiden a clear
            next step. Runs for EVERY terminal failure (validation, agent-failed,
            timeout, rate-limit) — so work is never lost, a fresh subagent can
            always pick up where this one died, and Jaiden can hand back a
            workaround instead of the run just going dark."""
            engine.mark_step_failed(run_id, idx, reason=reason)
            handoff_path = ""
            try:
                output_note = engine._read_task_output_note(task_id) if task_id else ""
                partial_output = ""
                if output_note:
                    note_path = Path.home() / "Documents" / "RaphBrain" / output_note
                    if note_path.exists():
                        partial_output = note_path.read_text()
                handoff_path = write_handoff_via_ollama(
                    task=run_snapshot.get("task_raw", ""),
                    session_name=task_id or f"{run_id}-step{idx}",
                    partial_output=partial_output,
                    cause=reason,
                )
                # Mirror into the project's agents/ folder so the next fresh agent
                # finds it during its RaphBrain scan.
                if handoff_path and run_snapshot.get("project"):
                    project = run_snapshot["project"]
                    # Prepend a machine-readable marker so the `handoffs`/`resume`
                    # commands know which repo to resume into (see _parse_handoff_meta).
                    hp = Path(handoff_path)
                    hp.write_text(
                        f'<!-- hermes-meta project="{project}" run="{run_id}" -->\n'
                        + hp.read_text()
                    )
                    # Registry is the source of truth for the vault folder — capitalize()
                    # misroutes hyphenated projects (finance-tracker → Finance-tracker orphan).
                    _proj = resolve_project(project)
                    vault_dir = (_proj.raphbrain_dir if _proj else None) or project.capitalize()
                    agents_dir = (
                        Path.home() / "Documents" / "RaphBrain" / "Projects" / vault_dir / "agents"
                    )
                    agents_dir.mkdir(parents=True, exist_ok=True)
                    mirror = agents_dir / f"hermes-handoff-{task_id or idx}.md"
                    mirror.write_text(hp.read_text())
                    log.info(f"[orchestrate] Handoff mirrored to: {mirror}")
            except Exception as exc:
                log.warning(f"[orchestrate] handoff generation failed: {exc}")

            handoff_line = f"\nHandoff for a fresh agent: {handoff_path}" if handoff_path else ""
            _send_reply(
                hermes_config,
                f"⚠️ Blocked on {role}: {reason}{handoff_line}\n\n"
                f"Reply [HERMES] abort to stop, or send a corrected task to work around it.",
            )

        final_status = engine.poll_step_completion(run_id, idx, task_id)

        if final_status in ("done", "needs-review"):
            if final_status == "needs-review":
                log.warning(f"[orchestrate] Step {idx} ({role}) needs-review — treating as done")
            output_path = engine._read_task_output_note(task_id)

            # Validate output note schema before advancing the pipeline.
            if output_path:
                valid, reason = validate_step_output(role, output_path)
                if not valid:
                    log.error(
                        f"[orchestrate] Schema validation failed step {idx} ({role}): {reason}"
                    )
                    _finalize_step_failure(f"Output schema validation failed: {reason}")
                    return

            pr_url = None
            if role == "deployer" and output_path:
                pr_url = engine._extract_pr_url(output_path)
            engine.mark_step_done(run_id, idx, output_path=output_path, pr_url=pr_url)

            # Milestone notification
            try:
                run_now = engine.get_run(run_id)
                step_now = run_now["pipeline"][idx]
                started = step_now.get("started_at", "")
                completed = step_now.get("completed_at", "")
                duration = _format_duration(started, completed) if started and completed else "??"
                pipeline = run_now["pipeline"]
                next_roles = [
                    s["role"] for s in pipeline[idx + 1 :] if s.get("status") == "pending"
                ]
                next_label = next_roles[0] if next_roles else "done"
                milestone_msg = (
                    f"✓ {role} done ({duration}) — {run_now['project']}\nNext: {next_label}"
                )
                _send_reply(hermes_config, milestone_msg)
            except Exception as exc:
                log.warning(f"[orchestrate] Failed to send milestone notification: {exc}")

        else:
            # Auto-retry once for transient failures (failed / timeout).
            # rate-limited is never retried — it requires waiting for quota reset.
            run_now = engine.get_run(run_id)
            retry_count = run_now["pipeline"][idx].get("retry_count", 0)
            if final_status in ("failed", "timeout") and retry_count < STEP_MAX_RETRIES:
                log.warning(
                    f"[orchestrate] Step {idx} ({role}) got {final_status!r} — "
                    f"retrying in {STEP_RETRY_DELAY_S}s (attempt {retry_count + 1}/{STEP_MAX_RETRIES})"
                )
                engine.reset_step_for_retry(run_id, idx)
                time.sleep(STEP_RETRY_DELAY_S)
                fresh_run = engine.get_run(run_id)
                _dispatch_one_step(run_id, idx, fresh_run["pipeline"][idx], fresh_run)
                return

            reason_map = {
                "failed": "Agent task reported failed",
                "rate-limited": "Claude Code rate-limited — retry manually after reset",
                "timeout": "Step exceeded hard timeout",
            }
            _finalize_step_failure(reason_map.get(final_status, final_status))

    log.info(f"[orchestrate] Pipeline thread started for run {run_id}")
    try:
        while True:
            run = engine.get_run(run_id)
            if run["status"] in ("failed", "aborted", "done"):
                break

            pipeline = run["pipeline"]
            next_steps = engine._find_next_pending_steps(pipeline)

            if not next_steps:
                # No more pending steps — finalise the run
                any_failed = any(s["status"] == "failed" for s in pipeline)
                final_status = "failed" if any_failed else "done"
                engine._update_run_fields(
                    run_id,
                    {
                        "status": final_status,
                        "completed_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                    },
                )
                log.info(f"[orchestrate] Run {run_id} complete — status={final_status}")
                break

            if len(next_steps) == 1:
                idx, step = next_steps[0]
                _dispatch_one_step(run_id, idx, step, run)
            else:
                # Parallel group — spawn sub-threads, wait for all
                log.info(
                    f"[orchestrate] Parallel group ({len(next_steps)} steps) for run {run_id}: "
                    f"{[s['role'] for _, s in next_steps]}"
                )
                threads = []
                for idx, step in next_steps:
                    t = threading.Thread(
                        target=_dispatch_one_step,
                        args=(run_id, idx, step, run),
                        daemon=True,
                        name=f"hermes-step-{run_id}-{idx}",
                    )
                    threads.append(t)
                    t.start()
                for t in threads:
                    t.join()
                log.info(f"[orchestrate] Parallel group finished for run {run_id}")

    except Exception as exc:
        log.error(
            f"[orchestrate] Pipeline thread crashed for run {run_id}: {exc}",
            exc_info=True,
        )
        try:
            engine._update_run_fields(
                run_id,
                {
                    "status": "failed",
                    "completed_at": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
                },
            )
        except Exception:
            pass
        _send_reply(hermes_config, f"❌ Pipeline thread crashed for run {run_id}. Check logs.")
        return

    # Send completion notification
    try:
        run = engine.get_run(run_id)
        project = run["project"]
        branch = run.get("branch", "")
        pr_url = run.get("pr_url")
        pipeline = run["pipeline"]
        done_count = sum(1 for s in pipeline if s["status"] == "done")
        step_count = len(pipeline)
        started_at = run.get("created_at", "")
        completed_at = run.get(
            "completed_at", datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
        )
        total_duration = _format_duration(started_at, completed_at) if started_at else "??"
        final_status = run["status"]

        if final_status == "done":
            if pr_url:
                completion_msg = (
                    f"✅ {project} — done\n"
                    f"PR: {pr_url}\n"
                    f"Duration: {total_duration}\n"
                    f"Steps: {done_count}/{step_count}"
                )
            else:
                completion_msg = (
                    f"✅ {project} — pipeline complete\n"
                    f"Duration: {total_duration}\n"
                    f"Steps: {done_count}/{step_count}"
                )
        elif final_status == "failed":
            # The step handler already texted a rich, actionable message when the step
            # died — "⚠️ Blocked on {role}: {reason}" plus the resume-handoff path. A
            # second "❌ failed, check logs" here only buries that with less info and
            # points you at the logs. Suppress it; the Blocked message is the last word.
            # ponytail: None → skip the send; the daily-note line below still records it.
            completion_msg = None
        elif final_status == "aborted":
            completion_msg = (
                f"\U0001f6d1 Run aborted: {project} / {branch}\n"
                f"Steps completed before abort: {done_count}/{step_count}"
            )
        else:
            completion_msg = f"\U0001f3c1 {project} run ended with status: {final_status}"

        if completion_msg:
            _send_reply(hermes_config, completion_msg)

        # Append a one-liner to today's RaphBrain daily note (with the failure reason).
        failed_step, failed_reason = "", ""
        if final_status == "failed":
            failed = next((s for s in pipeline if s["status"] == "failed"), None)
            if failed:
                failed_step = failed["role"]
                failed_reason = failed.get("reason", "")
        _append_pipeline_to_daily_note(
            project, branch, final_status, total_duration, failed_step, failed_reason
        )
    except Exception as exc:
        log.error(f"[orchestrate] Failed to send completion notification: {exc}")


def _direct_tasks_summary() -> str:
    """One line per live direct task, or '' if none."""
    with _DIRECT_LOCK:
        items = list(_DIRECT_TASKS.items())
    lines = []
    for name, info in items:
        elapsed = int(time.time() - info["started"])
        proj = info.get("project") or "—"
        lines.append(
            f"⚙️ {name} (project: {proj}) · {elapsed // 60}m{elapsed % 60:02d}s · {info['task'][:50]}"
        )
    return "\n".join(lines)


def _abort_direct_tasks() -> int:
    """Kill all live direct-task subprocesses. Returns how many were killed."""
    with _DIRECT_LOCK:
        procs = [(n, i["proc"]) for n, i in _DIRECT_TASKS.items()]
    for name, proc in procs:
        try:
            proc.kill()
            log.info(f"[abort] Killed direct task {name}")
        except Exception as exc:
            log.warning(f"[abort] Failed to kill {name}: {exc}")
    return len(procs)


def orchestrate_task(task_text: str, config: dict) -> str:
    """
    Route an incoming task through the planner.

    Both paths return a start-confirmation string immediately and report the
    real result later on their own channel:
    - Direct tasks: run_task() runs the agent in a background thread and sends
      the result via on_complete when the process exits.
    - Pipeline tasks: create a run file, start the engine in a daemon thread.

    config is the loaded config.yaml dict — needed for notification channel.
    """
    # Abort shortcut — intercept before planner so a rate-limited/stuck run
    # can always be cancelled without spinning up another pipeline.
    if task_text.strip().lower().startswith("abort"):
        killed = _abort_direct_tasks()
        engine = RunEngine()
        active = engine.get_active_run()
        msgs = []
        if killed:
            msgs.append(f"🛑 Killed {killed} direct task(s).")
        if active:
            try:
                engine.abort_run(active["id"])
                msgs.append(
                    f"🛑 Aborted run {active['id']} — "
                    f"{active.get('project', 'unknown')} / {active.get('branch', '')}"
                )
            except Exception as exc:
                log.warning(f"[orchestrate] abort_run failed: {exc}")
                msgs.append(f"⚠️ Abort failed: {exc}")
        return "\n".join(msgs) if msgs else "ℹ️ Nothing active to abort."

    # Status shortcut — fast local read of run state. Must intercept before the
    # planner, else "status" classifies as a direct task and spawns a 30-min
    # Claude session that blocks the whole poll loop.
    if task_text.strip().lower().rstrip("?") in (
        "status",
        "what's the status",
        "whats the status",
        "hermes status",
    ):
        engine = RunEngine()
        active = engine.get_active_run()
        direct = _direct_tasks_summary()
        if active:
            steps = active.get("pipeline", [])
            done = sum(1 for s in steps if s.get("status") == "done")
            cur = next(
                (s["role"] for s in steps if s.get("status") == "running"),
                next((s["role"] for s in steps if s.get("status") == "pending"), "—"),
            )
            started = active.get("created_at") or ""
            now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
            elapsed = _format_duration(started, now) if started else "?"
            pipeline_status = (
                f"🟢 {active.get('project', '?')} [Tier {active.get('tier', '?')}] "
                f"run {active['id']}\n"
                f"Step: {cur} ({done}/{len(steps)} done) · {elapsed}\n"
                f"Branch: {active.get('branch', '')}"
            )
        else:
            recent = engine.list_runs(limit=1)
            if recent:
                r = recent[0]
                pipeline_status = (
                    f"⚪️ No active pipeline run.\n"
                    f"Last: {r.get('project', '?')} run {r.get('id', '?')} → {r.get('status', '?')}"
                )
            else:
                pipeline_status = "⚪️ No active pipeline run."
        return f"{pipeline_status}\n\n{direct}".rstrip() if direct else pipeline_status

    # Discovery commands — help Jaiden drive from a phone without remembering the grammar.
    _cmd = task_text.strip().lower().rstrip("?")
    if _cmd in ("projects", "list projects"):
        return "Known projects:\n" + "\n".join(f"• {n}" for n in project_names())
    if _cmd in ("handoffs", "handoff", "pending"):
        return _list_handoffs()
    if _cmd in ("handoffs clear", "clear handoffs"):
        return _clear_handoffs()
    # Only intercept `resume` (bare → list) or `resume <n> [project]` — NOT a natural
    # task that merely starts with the word ("resume the deploy refactor"), which must
    # still route to the planner.
    if _cmd == "resume" or (
        _cmd.startswith("resume ") and _cmd[len("resume ") :].lstrip()[:1].isdigit()
    ):
        return _resume_handoff(_cmd[len("resume") :].strip(), config)
    if _cmd in ("help", "commands", "menu"):
        return (
            "Hermes commands:\n"
            "• on <project>, <task> — run in a project (e.g. `on alphabot, fix the rebalance bug`)\n"
            "• <task> — I'll infer the project\n"
            "• status — current run\n"
            "• abort — cancel the active run\n"
            "• handoffs — list unfinished runs you can resume\n"
            "• resume <n> — pick up handoff #n where it stopped (add a project to override, e.g. `resume 2 alphabot`)\n"
            "• projects — list known projects"
        )

    result: PlannerResult = classify_task(task_text)
    log.info(
        f"[orchestrate] Classified: tier={result.tier} project={result.project!r} "
        f"is_direct={result.is_direct} steps={len(result.pipeline)}"
    )

    # Scaffold task — create project skeleton, return result synchronously
    if result.scaffold_project:
        log.info(f"[orchestrate] Scaffold task — project={result.scaffold_project!r}")
        return run_scaffold(result.scaffold_project)

    # Direct task — runs in the background; result is sent back on completion.
    if result.is_direct:
        log.info("[orchestrate] Direct task — routing to run_task()")
        proj = resolve_project(result.project)
        return run_task(
            task_text,
            on_complete=lambda r: _send_reply(config, r[:4096]),
            project=result.project if proj else None,
            cwd=(proj.repo if (proj and proj.repo) else None),
        )

    # Pipeline task — fail loud on an unknown project rather than dispatching an
    # agent that would silently run in $HOME against nothing.
    proj = resolve_project(result.project)
    if not proj or not proj.repo:
        known = ", ".join(project_names())
        log.warning(f"[orchestrate] Refusing pipeline for unresolvable project {result.project!r}")
        return (
            f"❓ Couldn't map that to a project with a repo (got {result.project!r}).\n"
            f"Try prefixing it, e.g. `on arbiter, …`.\nKnown: {known}"
        )

    engine = RunEngine()
    runner = AgentRunner()

    try:
        run = engine.create_run(task_raw=task_text, result=result)
    except RuntimeError as exc:
        # Another run is already active — queue not yet supported
        log.warning(f"[orchestrate] create_run blocked: {exc}")
        return f"⚠️ {exc}\nSend [HERMES] abort to cancel the current run first."

    run_id = run["id"]
    pipeline_summary = " → ".join(s.role for s in result.pipeline)

    start_msg = (
        f"\U0001f4cb [Tier {result.tier}] {result.project} — {pipeline_summary}\n\n"
        f"Starting now. I'll ping you at each milestone.\n"
        f"Branch: {result.branch_name}"
    )

    # Set run to running before spawning the thread
    engine._update_run_field(run_id, "status", "running")

    t = threading.Thread(
        target=_run_pipeline,
        args=(run_id, engine, runner, config),
        daemon=True,
        name=f"hermes-pipeline-{run_id}",
    )
    t.start()
    log.info(f"[orchestrate] Pipeline thread started: run={run_id} project={result.project}")

    return start_msg


class TelegramPoller:
    """
    Polls Telegram Bot API for new messages.
    Uses long-offset tracking in config/telegram_state.json to avoid reprocessing.
    Replies via sendMessage API.
    """

    STATE_FILE = Path.home() / "hermes" / "config" / "telegram_state.json"

    def __init__(self, config):
        self.cfg = config["trigger"]["telegram"]
        self.hermes_cfg = config
        self.chat_id = self.cfg["chat_id"]
        self.prefix = self.cfg.get("trigger_prefix", "[HERMES]")
        self.token = keyring.get_password(
            self.cfg["bot_token_keychain_service"],
            self.cfg["bot_token_keychain_account"],
        )
        self.offset = self._load_offset()
        log.info(f"Telegram poller ready — chat_id={self.chat_id} offset={self.offset}")

    def _load_offset(self) -> int:
        try:
            if self.STATE_FILE.exists():
                data = json.loads(self.STATE_FILE.read_text())
                return int(data.get("offset", 0))
        except Exception:
            pass
        return 0

    def _save_offset(self, offset: int):
        self.STATE_FILE.write_text(json.dumps({"offset": offset}))

    def poll(self):
        try:
            # Long-poll: getUpdates blocks up to 25s and returns the moment a message
            # arrives — near-instant pickup, far fewer requests than short-poll + sleep.
            resp = requests.get(
                f"https://api.telegram.org/bot{self.token}/getUpdates",
                params={"offset": self.offset, "timeout": 25},
                timeout=30,
            )
            if not resp.ok:
                log.error(f"Telegram getUpdates failed: {_redact_token(resp.text, self.token)}")
                return

            updates = resp.json().get("result", [])
            for update in updates:
                self.offset = update["update_id"] + 1
                self._save_offset(self.offset)

                msg = update.get("message", {})
                if not msg or msg.get("chat", {}).get("id") != self.chat_id:
                    continue

                text = msg.get("text", "").strip()
                if not text:
                    continue

                task = text[len(self.prefix) :].strip() if text.startswith(self.prefix) else text
                self._journal(update["update_id"], task)
                log.info(f"Telegram task: {task[:80]}...")
                # Process off the poll loop: a slow classification (Ollama ~15-30s)
                # must not freeze pickup of the next message. Ack immediately.
                self._reply("👀 on it")
                threading.Thread(
                    target=self._process, args=(task,), daemon=True, name="hermes-tg-task"
                ).start()

        except (requests.exceptions.Timeout, requests.exceptions.ConnectionError) as exc:
            # Long-poll read/connect timeouts are normal idle behaviour — the server
            # holds getUpdates open, the odd hiccup just means the next poll retries.
            # Log at DEBUG so genuine errors below aren't buried under this noise.
            # ponytail: DEBUG-only, no consecutive-failure escalation — a real outage
            # shows up as tasks not getting picked up, which you notice directly.
            log.debug(f"Telegram poll transient: {_redact_token(str(exc), self.token)}")
        except Exception as exc:
            log.error(f"Telegram poll error: {_redact_token(str(exc), self.token)}")

    def _process(self, task: str):
        try:
            reply = orchestrate_task(task, self.hermes_cfg)
            self._reply(reply[:4096])
        except Exception as task_exc:
            log.error(f"Task execution error: {task_exc}", exc_info=True)
            self._reply(f"❌ Error: {task_exc}")

    def _journal(self, update_id: int, task: str):
        """Append the raw message before processing so a daemon crash mid-task
        leaves a trace instead of silently losing it (offset already advanced)."""
        try:
            jpath = Path.home() / "hermes" / "logs" / "telegram-journal.log"
            with jpath.open("a") as f:
                f.write(f"{update_id}\t{task}\n")
        except Exception:
            pass

    def _reply(self, message: str):
        _send_telegram(self.token, self.chat_id, message)


def main():
    log.info("=== Hermes starting up ===")
    config = load_config()

    subprocess.run([str(Path.home() / "hermes" / "scripts" / "check-connectivity.sh")])

    # Recover crash-orphaned runs ONCE here — never per-message (see RunEngine).
    RunEngine().startup_recover_and_cleanup()

    # Probe model aliases so routing auto-downgrades if a tier (e.g. Fable) has left
    # the plan — a run must never die on a model the CLI can no longer reach.
    probe_models()

    log.info("Trigger: Telegram polling")
    poller = TelegramPoller(config)
    while True:
        poller.poll()
        time.sleep(1)  # poll() long-polls up to 25s; this is just a loop breather


if __name__ == "__main__":
    main()
