#!/usr/bin/env python3
"""
Hermes — persistent orchestration agent for Jaiden's Mac Mini.
Listens for commands, spawns Claude Code sessions via tmux, reports back.
"""

import subprocess
import logging
import time
import threading
import yaml
import json
import imaplib
import email
import smtplib
import shlex
import keyring
import requests
from datetime import datetime
from pathlib import Path
from email.mime.text import MIMEText
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

from planner import classify_task, PlannerResult
from run_engine import RunEngine
from agent_runner import AgentRunner

CONFIG_PATH = Path.home() / "hermes" / "config" / "config.yaml"
STEP_MAX_RETRIES = 1  # max automatic retries per step (not applicable to rate-limited)
STEP_RETRY_DELAY_S = 10  # seconds to wait before retrying a failed step
LOG_PATH = Path.home() / "hermes" / "logs" / "hermes.log"

# Ensure logs directory exists before configuring file handler
LOG_PATH.parent.mkdir(parents=True, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.FileHandler(LOG_PATH), logging.StreamHandler()],
)
log = logging.getLogger("hermes")


def load_config():
    with open(CONFIG_PATH) as f:
        return yaml.safe_load(f)


def write_handoff_via_ollama(task: str, session_name: str, partial_output: str) -> str:
    """When Claude Code times out, use a local Ollama model to write a handoff note."""
    log.info(f"Writing handoff via Ollama for: {session_name}")

    prompt = f"""You are writing a handoff note for an AI agent that ran out of time mid-task.
Your job: read what was done and write a clear, actionable handoff so the next agent can resume without any human help.

ORIGINAL TASK:
{task}

PARTIAL OUTPUT (everything that ran before timeout):
{partial_output[:4000]}

Write a handoff note in this exact markdown format:

## What Was Completed
(bullet list of finished work — be specific, include file names and line numbers if mentioned)

## In Progress At Timeout
(what was being worked on when time ran out)

## Still Needs To Be Done
(remaining steps to fully complete the original task)

## How To Resume
(exact commands or steps the next agent should run first)

## Files Modified
(list any files that were changed, created, or deleted)

Be specific and factual. Only include what is supported by the partial output above."""

    try:
        import json as _json
        import urllib.request as _urllib

        payload = _json.dumps(
            {"model": "llama3.1:8b", "prompt": prompt, "stream": False}
        ).encode()
        req = _urllib.Request(
            "http://localhost:11434/api/generate",
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with _urllib.urlopen(req, timeout=120) as resp:
            response_text = (
                _json.loads(resp.read().decode()).get("response", "").strip()
            )

        if not response_text:
            log.error("Ollama handoff generation returned empty response")
            return ""

        handoff_dir = Path.home() / "Documents" / "RaphBrain" / "Projects" / "handoffs"
        handoff_dir.mkdir(parents=True, exist_ok=True)
        handoff_path = handoff_dir / f"{session_name}-handoff.md"
        handoff_path.write_text(
            f"# Auto-Handoff — {session_name}\n"
            f"*Generated by Ollama (Claude Code usage limit reached)*\n"
            f"*{datetime.now().strftime('%Y-%m-%d %H:%M')}*\n\n"
            f"> **Original task:** {task[:200]}\n\n"
            f"{response_text}\n"
        )
        log.info(f"Handoff written: {handoff_path}")
        return str(handoff_path)
    except TimeoutError:
        log.error("Ollama handoff timed out after 120s")
        return ""
    except OSError:
        log.error("Ollama not found — is it installed?")
        return ""


def run_task(task: str, session_name: str = None) -> str:
    """Spawn a tmux session running Claude Code with the given task."""
    if not session_name:
        session_name = f"hermes-{int(time.time())}"

    log.info(f"Spawning task in tmux session: {session_name}")
    log.info(f"Task: {task[:120]}...")

    task_file = Path.home() / "hermes" / "tasks" / f"{session_name}.md"
    task_file.write_text(f"# Hermes Task\n\n{task}\n")

    log_file = Path.home() / "hermes" / "logs" / f"{session_name}.log"

    safe_task_file = shlex.quote(str(task_file))
    safe_log_file = shlex.quote(str(log_file))

    shell_cmd = (
        f'claude --print "$(cat {safe_task_file})" '
        f"2>&1 | tee {safe_log_file}; echo 'HERMES_DONE' >> {safe_log_file}"
    )

    cmd = [
        "tmux",
        "new-session",
        "-d",
        "-s",
        session_name,
        "-x",
        "220",
        "-y",
        "50",
        shell_cmd,
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)

    if result.returncode != 0:
        log.error(f"Failed to spawn tmux session: {result.stderr}")
        return f"ERROR: {result.stderr}"

    timeout = 1800
    elapsed = 0
    while elapsed < timeout:
        time.sleep(5)
        elapsed += 5
        if log_file.exists():
            content = log_file.read_text()
            if "HERMES_DONE" in content:
                log.info(f"Task complete: {session_name}")
                return content.replace("HERMES_DONE", "").strip()

    # Timeout — use Ollama to write a handoff so work isn't lost
    log.warning(f"Task timed out: {session_name} — triggering Ollama handoff writer")
    partial = log_file.read_text() if log_file.exists() else "(no output captured)"
    handoff_path = write_handoff_via_ollama(task, session_name, partial)

    if handoff_path:
        return (
            f"Task {session_name} timed out after {timeout}s. "
            f"Handoff written to: {handoff_path} — resume when Claude Code resets."
        )
    return (
        f"Task {session_name} timed out after {timeout}s. "
        f"Check tmux: tmux attach -t {session_name}"
    )


# ---------------------------------------------------------------------------
# Pipeline orchestration helpers
# ---------------------------------------------------------------------------


def _format_duration(started_iso: str, ended_iso: str) -> str:
    """Return a human-readable duration like '2m 14s'."""
    try:
        fmt = "%Y-%m-%dT%H:%M:%SZ"
        delta = int(
            (
                datetime.strptime(ended_iso, fmt) - datetime.strptime(started_iso, fmt)
            ).total_seconds()
        )
        if delta < 0:
            delta = 0
        mins, secs = divmod(delta, 60)
        return f"{mins}m {secs:02d}s" if mins else f"{secs}s"
    except Exception:
        return "??"


def _send_imessage(reply_to: str, message: str) -> None:
    """Send an iMessage to reply_to (phone number or Apple ID) via osascript."""
    if not reply_to:
        log.info(f"[iMessage] (no reply_to configured): {message[:80]}")
        return
    safe = message.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    script = f"""tell application "Messages"
    set targetService to 1st service whose service type = iMessage
    set targetBuddy to buddy "{reply_to}" of targetService
    send "{safe}" to targetBuddy
end tell"""
    result = subprocess.run(
        ["osascript", "-e", script], capture_output=True, text=True, timeout=10
    )
    if result.returncode != 0:
        log.error(f"iMessage send failed: {result.stderr.strip()}")
    else:
        log.info(f"iMessage sent to {reply_to}: {message[:80]}")


def _send_telegram(token: str, chat_id: int, message: str) -> None:
    """Send a message to a Telegram chat via Bot API."""
    try:
        resp = requests.post(
            f"https://api.telegram.org/bot{token}/sendMessage",
            json={"chat_id": chat_id, "text": message},
            timeout=10,
        )
        if not resp.ok:
            log.error(f"Telegram send failed: {resp.text}")
        else:
            log.info(f"Telegram message sent to {chat_id}: {message[:80]}")
    except Exception as exc:
        log.error(f"Telegram send error: {exc}")


def _send_reply(config: dict, message: str) -> None:
    """Send a reply via whichever channel is active (telegram or imessage)."""
    method = config.get("trigger", {}).get("method", "imessage")
    if method == "telegram":
        tcfg = config["trigger"]["telegram"]
        token = keyring.get_password(
            tcfg["bot_token_keychain_service"], tcfg["bot_token_keychain_account"]
        )
        _send_telegram(token, tcfg["chat_id"], message)
    else:
        reply_to = config.get("trigger", {}).get("imessage", {}).get("reply_to", "")
        _send_imessage(reply_to, message)


def _run_pipeline(
    run_id: str, engine: RunEngine, runner: AgentRunner, hermes_config: dict
) -> None:
    """
    Background thread: drives a full pipeline run to completion.

    For each step (or parallel group of steps):
      1. Call AgentRunner.dispatch_step() -> task_id  (non-blocking)
      2. Call engine.mark_step_started(run_id, idx, task_id)
      3. Call engine.poll_step_completion()  (blocks until done/failed/timeout)
      4. Call engine.mark_step_done() or engine.mark_step_failed()
      5. Send milestone notification

    Parallel groups are dispatched as sub-threads and joined before continuing.
    Completion/failure notification is sent when the last step resolves.
    """

    def _dispatch_one_step(
        run_id: str, idx: int, step: dict, run_snapshot: dict
    ) -> None:
        """Dispatch a single step, poll to completion, update engine state."""
        role = step["role"]
        try:
            task_id = runner.dispatch_step(
                step=step,
                run=run_snapshot,
                task_description=run_snapshot["task_raw"],
            )
        except Exception as exc:
            log.error(f"[orchestrate] dispatch_step failed for role={role}: {exc}")
            engine.mark_step_failed(run_id, idx, reason=f"dispatch failed: {exc}")
            return

        engine.mark_step_started(run_id, idx, task_id)
        log.info(f"[orchestrate] Step {idx} ({role}) dispatched as task {task_id}")

        final_status = engine.poll_step_completion(run_id, idx, task_id)

        if final_status in ("done", "needs-review"):
            if final_status == "needs-review":
                log.warning(
                    f"[orchestrate] Step {idx} ({role}) needs-review — treating as done"
                )
            output_path = engine._read_task_output_note(task_id)
            pr_url = None
            if role == "deployer" and output_path:
                pr_url = engine._extract_pr_url(output_path)
            engine.mark_step_done(run_id, idx, output_path=output_path, pr_url=pr_url)

            # Milestone notification
            try:
                run_now = engine.get_run(run_id)
                step_now = run_now["pipeline"][idx]
                started = step_now.get("started_at", "")
                completed = step_now.get("completed_at", "")
                duration = (
                    _format_duration(started, completed)
                    if started and completed
                    else "??"
                )
                pipeline = run_now["pipeline"]
                next_roles = [
                    s["role"]
                    for s in pipeline[idx + 1 :]
                    if s.get("status") == "pending"
                ]
                next_label = next_roles[0] if next_roles else "done"
                milestone_msg = (
                    f"✓ {role} done ({duration}) — {run_now['project']}\n"
                    f"Next: {next_label}"
                )
                _send_reply(hermes_config, milestone_msg)
            except Exception as exc:
                log.warning(
                    f"[orchestrate] Failed to send milestone notification: {exc}"
                )

        else:
            # Auto-retry once for transient failures (failed / timeout).
            # rate-limited is never retried — it requires waiting for quota reset.
            run_now = engine.get_run(run_id)
            retry_count = run_now["pipeline"][idx].get("retry_count", 0)
            if final_status in ("failed", "timeout") and retry_count < STEP_MAX_RETRIES:
                log.warning(
                    f"[orchestrate] Step {idx} ({role}) got {final_status!r} — "
                    f"retrying in {STEP_RETRY_DELAY_S}s (attempt {retry_count + 1}/{STEP_MAX_RETRIES})"
                )
                engine.reset_step_for_retry(run_id, idx)
                time.sleep(STEP_RETRY_DELAY_S)
                fresh_run = engine.get_run(run_id)
                _dispatch_one_step(run_id, idx, fresh_run["pipeline"][idx], fresh_run)
                return

            reason_map = {
                "failed": "Agent task reported failed",
                "rate-limited": "Claude Code rate-limited — retry manually after reset",
                "timeout": "Step exceeded hard timeout",
            }
            reason = reason_map.get(final_status, final_status)
            engine.mark_step_failed(run_id, idx, reason=reason)
            blocker_msg = (
                f"⚠️ Blocked on {role}: {reason}\n\n"
                f"Reply with:\n"
                f"[HERMES] abort — abort the run"
            )
            _send_reply(hermes_config, blocker_msg)

    log.info(f"[orchestrate] Pipeline thread started for run {run_id}")
    try:
        while True:
            run = engine.get_run(run_id)
            if run["status"] in ("failed", "aborted", "done"):
                break

            pipeline = run["pipeline"]
            next_steps = engine._find_next_pending_steps(pipeline)

            if not next_steps:
                # No more pending steps — finalise the run
                any_failed = any(s["status"] == "failed" for s in pipeline)
                final_status = "failed" if any_failed else "done"
                engine._update_run_fields(
                    run_id,
                    {
                        "status": final_status,
                        "completed_at": datetime.utcnow().strftime(
                            "%Y-%m-%dT%H:%M:%SZ"
                        ),
                    },
                )
                log.info(f"[orchestrate] Run {run_id} complete — status={final_status}")
                break

            if len(next_steps) == 1:
                idx, step = next_steps[0]
                _dispatch_one_step(run_id, idx, step, run)
            else:
                # Parallel group — spawn sub-threads, wait for all
                log.info(
                    f"[orchestrate] Parallel group ({len(next_steps)} steps) for run {run_id}: "
                    f"{[s['role'] for _, s in next_steps]}"
                )
                threads = []
                for idx, step in next_steps:
                    t = threading.Thread(
                        target=_dispatch_one_step,
                        args=(run_id, idx, step, run),
                        daemon=True,
                        name=f"hermes-step-{run_id}-{idx}",
                    )
                    threads.append(t)
                    t.start()
                for t in threads:
                    t.join()
                log.info(f"[orchestrate] Parallel group finished for run {run_id}")

    except Exception as exc:
        log.error(
            f"[orchestrate] Pipeline thread crashed for run {run_id}: {exc}",
            exc_info=True,
        )
        try:
            engine._update_run_fields(
                run_id,
                {
                    "status": "failed",
                    "completed_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
                },
            )
        except Exception:
            pass
        _send_reply(
            hermes_config, f"❌ Pipeline thread crashed for run {run_id}. Check logs."
        )
        return

    # Send completion notification
    try:
        run = engine.get_run(run_id)
        project = run["project"]
        branch = run.get("branch", "")
        pr_url = run.get("pr_url")
        pipeline = run["pipeline"]
        done_count = sum(1 for s in pipeline if s["status"] == "done")
        step_count = len(pipeline)
        started_at = run.get("created_at", "")
        completed_at = run.get(
            "completed_at", datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
        )
        total_duration = (
            _format_duration(started_at, completed_at) if started_at else "??"
        )
        final_status = run["status"]

        if final_status == "done":
            if pr_url:
                completion_msg = (
                    f"✅ {project} — done\n"
                    f"PR: {pr_url}\n"
                    f"Duration: {total_duration}\n"
                    f"Steps: {done_count}/{step_count}"
                )
            else:
                completion_msg = (
                    f"✅ {project} — pipeline complete\n"
                    f"Duration: {total_duration}\n"
                    f"Steps: {done_count}/{step_count}"
                )
        elif final_status == "failed":
            failed_step = next(
                (s["role"] for s in pipeline if s["status"] == "failed"), "unknown"
            )
            completion_msg = f"❌ {project} failed at step {failed_step}. Check logs."
        elif final_status == "aborted":
            completion_msg = (
                f"\U0001f6d1 Run aborted: {project} / {branch}\n"
                f"Steps completed before abort: {done_count}/{step_count}"
            )
        else:
            completion_msg = (
                f"\U0001f3c1 {project} run ended with status: {final_status}"
            )

        _send_reply(hermes_config, completion_msg)
    except Exception as exc:
        log.error(f"[orchestrate] Failed to send completion notification: {exc}")


def orchestrate_task(task_text: str, config: dict) -> str:
    """
    Route an incoming task through the planner.

    - Direct tasks (status checks, short queries): forwarded to run_task() synchronously.
    - Pipeline tasks: create a run file, start the engine in a daemon thread,
      return a start-confirmation string immediately (sent as the reply).

    config is the loaded config.yaml dict — needed for notification channel.
    """
    # Abort shortcut — intercept before planner so a rate-limited/stuck run
    # can always be cancelled without spinning up another pipeline.
    if task_text.strip().lower().startswith("abort"):
        engine = RunEngine()
        active = engine.get_active_run()
        if active:
            try:
                engine.abort_run(active["id"])
                project = active.get("project", "unknown")
                branch = active.get("branch", "")
                return f"🛑 Aborted run {active['id']} — {project} / {branch}"
            except Exception as exc:
                log.warning(f"[orchestrate] abort_run failed: {exc}")
                return f"⚠️ Abort failed: {exc}"
        return "ℹ️ No active run to abort."

    result: PlannerResult = classify_task(task_text)
    log.info(
        f"[orchestrate] Classified: tier={result.tier} project={result.project!r} "
        f"is_direct={result.is_direct} steps={len(result.pipeline)}"
    )

    # Direct task — use existing synchronous run_task()
    if result.is_direct:
        log.info("[orchestrate] Direct task — routing to run_task()")
        return run_task(task_text)

    # Pipeline task
    engine = RunEngine()
    runner = AgentRunner()

    try:
        run = engine.create_run(task_raw=task_text, result=result)
    except RuntimeError as exc:
        # Another run is already active — queue not yet supported
        log.warning(f"[orchestrate] create_run blocked: {exc}")
        return f"⚠️ {exc}\nSend [HERMES] abort to cancel the current run first."

    run_id = run["id"]
    pipeline_summary = " → ".join(s.role for s in result.pipeline)

    start_msg = (
        f"\U0001f4cb [Tier {result.tier}] {result.project} — {pipeline_summary}\n\n"
        f"Starting now. I'll ping you at each milestone.\n"
        f"Branch: {result.branch_name}"
    )

    # Set run to running before spawning the thread
    engine._update_run_field(run_id, "status", "running")

    t = threading.Thread(
        target=_run_pipeline,
        args=(run_id, engine, runner, config),
        daemon=True,
        name=f"hermes-pipeline-{run_id}",
    )
    t.start()
    log.info(
        f"[orchestrate] Pipeline thread started: run={run_id} project={result.project}"
    )

    return start_msg


def notify(config: dict, subject: str, body: str):
    method = config["notification"]["method"]

    if method == "log_only":
        log.info(f"NOTIFY: {subject} | {body}")
        return

    if method == "email":
        cfg = config["notification"]["email"]
        try:
            password = keyring.get_password("hermes-gmail", "hermes")
            msg = MIMEText(body)
            msg["Subject"] = f"[Hermes] {subject}"
            msg["From"] = cfg["from"]
            msg["To"] = cfg["to"]

            with smtplib.SMTP(cfg["smtp_host"], cfg["smtp_port"]) as server:
                server.starttls()
                server.login(cfg["from"], password)
                server.send_message(msg)
            log.info(f"Notification sent: {subject}")
        except Exception as e:
            log.error(f"Failed to send notification: {e}")


class TelegramPoller:
    """
    Polls Telegram Bot API for new messages.
    Uses long-offset tracking in config/telegram_state.json to avoid reprocessing.
    Replies via sendMessage API.
    """

    STATE_FILE = Path.home() / "hermes" / "config" / "telegram_state.json"

    def __init__(self, config):
        self.cfg = config["trigger"]["telegram"]
        self.hermes_cfg = config
        self.chat_id = self.cfg["chat_id"]
        self.prefix = self.cfg.get("trigger_prefix", "[HERMES]")
        self.token = keyring.get_password(
            self.cfg["bot_token_keychain_service"],
            self.cfg["bot_token_keychain_account"],
        )
        self.offset = self._load_offset()
        log.info(f"Telegram poller ready — chat_id={self.chat_id} offset={self.offset}")

    def _load_offset(self) -> int:
        try:
            if self.STATE_FILE.exists():
                data = json.loads(self.STATE_FILE.read_text())
                return int(data.get("offset", 0))
        except Exception:
            pass
        return 0

    def _save_offset(self, offset: int):
        self.STATE_FILE.write_text(json.dumps({"offset": offset}))

    def poll(self):
        try:
            resp = requests.get(
                f"https://api.telegram.org/bot{self.token}/getUpdates",
                params={"offset": self.offset, "timeout": 0},
                timeout=15,
            )
            if not resp.ok:
                log.error(f"Telegram getUpdates failed: {resp.text}")
                return

            updates = resp.json().get("result", [])
            for update in updates:
                self.offset = update["update_id"] + 1
                self._save_offset(self.offset)

                msg = update.get("message", {})
                if not msg:
                    continue

                # Only process messages from Jaiden's chat
                if msg.get("chat", {}).get("id") != self.chat_id:
                    continue

                text = msg.get("text", "").strip()
                if not text:
                    continue

                task = (
                    text[len(self.prefix) :].strip()
                    if text.startswith(self.prefix)
                    else text
                )
                log.info(f"Telegram task: {task[:80]}...")
                try:
                    reply = orchestrate_task(task, self.hermes_cfg)
                    self._reply(reply[:4096])
                except Exception as task_exc:
                    log.error(f"Task execution error: {task_exc}", exc_info=True)
                    self._reply(f"❌ Error: {task_exc}")

        except Exception as exc:
            log.error(f"Telegram poll error: {exc}")

    def _reply(self, message: str):
        _send_telegram(self.token, self.chat_id, message)


class iMessagePoller:
    """
    Polls Messages.app via osascript — no Full Disk Access required.
    Tracks last-checked timestamp in config/imessage_state.json.
    Replies via osascript -> Messages.app.
    """

    STATE_FILE = Path.home() / "hermes" / "config" / "imessage_state.json"

    def __init__(self, config):
        self.cfg = config["trigger"]["imessage"]
        self.reply_to = self.cfg.get("reply_to", "")
        self.prefix = self.cfg.get("trigger_prefix", "[HERMES]")
        self.hermes_cfg = config
        self.last_check = self._load_last_check()
        log.info(
            f"iMessage poller ready (osascript, no FDA) — "
            f"tracking from {self.last_check:%Y-%m-%d %H:%M:%S}"
        )

    def _load_last_check(self) -> datetime:
        try:
            if self.STATE_FILE.exists():
                data = json.loads(self.STATE_FILE.read_text())
                ts = data.get("last_check_ts")
                if ts:
                    return datetime.fromtimestamp(float(ts))
        except Exception:
            pass
        # First run: start from now so we don't replay old messages
        now = datetime.now()
        self._save_last_check(now)
        return now

    def _save_last_check(self, dt: datetime):
        self.STATE_FILE.write_text(json.dumps({"last_check_ts": dt.timestamp()}))

    def poll(self):
        now = datetime.now()
        # macOS AppleScript date string — no zero-padded day or hour
        cutoff_str = self.last_check.strftime("%B %-d, %Y at %-I:%M:%S %p")
        prefix_esc = self.prefix.replace('"', '\\"')

        script = f"""set cutoff to date "{cutoff_str}"
set triggerPrefix to "{prefix_esc}"
set output to ""
tell application "Messages"
    repeat with aChat in chats
        try
            set msgs to messages of aChat
            set msgCount to count of msgs
            set startIdx to msgCount - 19
            if startIdx < 1 then set startIdx to 1
            repeat with i from startIdx to msgCount
                set aMsg to item i of msgs
                try
                    if (date sent of aMsg) > cutoff then
                        set msgText to text of aMsg
                        if msgText starts with triggerPrefix then
                            set output to output & msgText & "|||HSEP|||"
                        end if
                    end if
                end try
            end repeat
        end try
    end repeat
end tell
return output"""

        result = subprocess.run(
            ["osascript", "-e", script], capture_output=True, text=True, timeout=30
        )

        self.last_check = now
        self._save_last_check(now)

        if result.returncode != 0:
            log.error(f"osascript poll error: {result.stderr.strip()}")
            return

        output = result.stdout.strip()
        if not output:
            return

        tasks = [m.strip() for m in output.split("|||HSEP|||") if m.strip()]
        for text in tasks:
            task = text[len(self.prefix) :].strip()
            log.info(f"iMessage task: {task[:80]}...")
            reply = orchestrate_task(task, self.hermes_cfg)
            self._reply(reply[:1500])

    def _reply(self, message: str):
        if not self.reply_to:
            log.info(f"[no reply_to configured] RESULT: {message}")
            return

        safe = message.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        script = f"""tell application "Messages"
    set targetService to 1st service whose service type = iMessage
    set targetBuddy to buddy "{self.reply_to}" of targetService
    send "{safe}" to targetBuddy
end tell"""

        result = subprocess.run(
            ["osascript", "-e", script], capture_output=True, text=True, timeout=10
        )
        if result.returncode != 0:
            log.error(f"iMessage reply failed: {result.stderr.strip()}")
        else:
            log.info(f"Reply sent via iMessage to {self.reply_to}")


class EmailPoller:
    def __init__(self, config):
        self.cfg = config["trigger"]["email"]
        self.hermes_cfg = config

    def poll(self):
        try:
            password = keyring.get_password(
                self.cfg["password_keychain_service"],
                self.cfg["password_keychain_account"],
            )
            mail = imaplib.IMAP4_SSL(self.cfg["imap_host"], self.cfg["imap_port"])
            mail.login(self.cfg["username"], password)
            mail.select("inbox")

            prefix = self.cfg["trigger_subject_prefix"]
            _, msgs = mail.search(None, f'(UNSEEN SUBJECT "{prefix}")')

            for num in msgs[0].split():
                _, data = mail.fetch(num, "(RFC822)")
                msg = email.message_from_bytes(data[0][1])
                subject = msg["subject"]
                task = subject.replace(prefix, "").strip()

                if msg.is_multipart():
                    for part in msg.walk():
                        if part.get_content_type() == "text/plain":
                            task += "\n\n" + part.get_payload(decode=True).decode()
                            break
                else:
                    task += "\n\n" + msg.get_payload(decode=True).decode()

                log.info(f"Received task via email: {task[:80]}...")
                mail.store(num, "+FLAGS", "\\Seen")

                result = run_task(task)
                notify(self.hermes_cfg, "Task complete", result[:2000])

            mail.logout()
        except Exception as e:
            log.error(f"Email poll error: {e}")


class FileWatcher(FileSystemEventHandler):
    def __init__(self, config):
        self.hermes_cfg = config

    def on_created(self, event):
        if event.is_directory or not event.src_path.endswith(".task"):
            return
        path = Path(event.src_path)
        log.info(f"Task file detected: {path.name}")
        task = path.read_text().strip()
        result = run_task(task, session_name=path.stem)
        notify(self.hermes_cfg, f"Task complete: {path.stem}", result[:2000])
        path.unlink()


class WebhookListener:
    def __init__(self, config):
        self.cfg = config["trigger"]["webhook"]
        self.hermes_cfg = config

    def run(self):
        from http.server import HTTPServer, BaseHTTPRequestHandler
        import hmac
        import hashlib

        secret = self.cfg["secret"].encode()
        hermes_cfg = self.hermes_cfg

        class Handler(BaseHTTPRequestHandler):
            def do_POST(self):
                length = int(self.headers.get("Content-Length", 0))
                body = self.rfile.read(length)
                sig = self.headers.get("X-Hermes-Signature", "")

                expected = hmac.new(secret, body, hashlib.sha256).hexdigest()
                if not hmac.compare_digest(sig, expected):
                    self.send_response(403)
                    self.end_headers()
                    return

                data = json.loads(body)
                task = data.get("task", "")
                log.info(f"Webhook task received: {task[:80]}...")

                self.send_response(202)
                self.end_headers()
                self.wfile.write(b'{"status": "accepted"}')

                result = run_task(task)
                notify(hermes_cfg, "Task complete", result[:2000])

            def log_message(self, *args):
                pass

        server = HTTPServer((self.cfg["host"], self.cfg["port"]), Handler)
        log.info(f"Webhook listener on port {self.cfg['port']}")
        server.serve_forever()


def main():
    log.info("=== Hermes starting up ===")
    config = load_config()
    method = config["trigger"]["method"]

    subprocess.run([str(Path.home() / "hermes" / "scripts" / "check-connectivity.sh")])

    if method == "telegram":
        log.info("Trigger: Telegram polling")
        poller = TelegramPoller(config)
        while True:
            poller.poll()
            time.sleep(config["trigger"]["telegram"]["poll_interval_seconds"])

    elif method == "imessage":
        log.info("Trigger: iMessage polling")
        poller = iMessagePoller(config)
        while True:
            poller.poll()
            time.sleep(config["trigger"]["imessage"]["poll_interval_seconds"])

    elif method == "email":
        log.info("Trigger: email polling")
        poller = EmailPoller(config)
        while True:
            poller.poll()
            time.sleep(config["trigger"]["email"]["poll_interval_seconds"])

    elif method == "file_watch":
        log.info(
            f"Trigger: file watch on {config['trigger']['file_watch']['watch_dir']}"
        )
        observer = Observer()
        handler = FileWatcher(config)
        observer.schedule(
            handler, config["trigger"]["file_watch"]["watch_dir"], recursive=False
        )
        observer.start()
        try:
            while True:
                time.sleep(1)
        except KeyboardInterrupt:
            observer.stop()
        observer.join()

    elif method == "webhook":
        log.info("Trigger: webhook")
        WebhookListener(config).run()


if __name__ == "__main__":
    main()
