#!/usr/bin/env python3
"""
Hermes — persistent orchestration agent for Jaiden's Mac Mini.
Listens for commands, spawns Claude Code sessions via tmux, reports back.
"""

import subprocess
import logging
import time
import threading
import yaml
import json
import imaplib
import email
import smtplib
import shutil
import keyring
import requests
from datetime import datetime
from pathlib import Path
from typing import Callable, Optional
from email.mime.text import MIMEText
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

from planner import classify_task, PlannerResult
from run_engine import RunEngine
from agent_runner import AgentRunner
from output_validator import validate_step_output
from project_registry import project_map_text, project_names, resolve as resolve_project
from scaffold_project import run_scaffold

CONFIG_PATH = Path.home() / "hermes" / "config" / "config.yaml"
STEP_MAX_RETRIES = 1  # max automatic retries per step (not applicable to rate-limited)
STEP_RETRY_DELAY_S = 10  # seconds to wait before retrying a failed step
LOG_PATH = Path.home() / "hermes" / "logs" / "hermes.log"

# Ensure logs directory exists before configuring file handler
LOG_PATH.parent.mkdir(parents=True, exist_ok=True)

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(message)s",
    handlers=[logging.FileHandler(LOG_PATH), logging.StreamHandler()],
)
log = logging.getLogger("hermes")


def load_config():
    with open(CONFIG_PATH) as f:
        return yaml.safe_load(f)


def write_handoff_via_ollama(task: str, session_name: str, partial_output: str) -> str:
    """When Claude Code times out, use a local Ollama model to write a handoff note."""
    log.info(f"Writing handoff via Ollama for: {session_name}")

    prompt = f"""You are writing a handoff note for an AI agent that ran out of time mid-task.
Your job: read what was done and write a clear, actionable handoff so the next agent can resume without any human help.

ORIGINAL TASK:
{task}

PARTIAL OUTPUT (everything that ran before timeout):
{partial_output[:4000]}

Write a handoff note in this exact markdown format:

## What Was Completed
(bullet list of finished work — be specific, include file names and line numbers if mentioned)

## In Progress At Timeout
(what was being worked on when time ran out)

## Still Needs To Be Done
(remaining steps to fully complete the original task)

## How To Resume
(exact commands or steps the next agent should run first)

## Files Modified
(list any files that were changed, created, or deleted)

Be specific and factual. Only include what is supported by the partial output above."""

    try:
        import json as _json
        import urllib.request as _urllib

        payload = _json.dumps({"model": "llama3.1:8b", "prompt": prompt, "stream": False}).encode()
        req = _urllib.Request(
            "http://localhost:11434/api/generate",
            data=payload,
            headers={"Content-Type": "application/json"},
            method="POST",
        )
        with _urllib.urlopen(req, timeout=120) as resp:
            response_text = _json.loads(resp.read().decode()).get("response", "").strip()

        if not response_text:
            log.error("Ollama handoff generation returned empty response")
            return ""

        handoff_dir = Path.home() / "Documents" / "RaphBrain" / "Projects" / "handoffs"
        handoff_dir.mkdir(parents=True, exist_ok=True)
        handoff_path = handoff_dir / f"{session_name}-handoff.md"
        handoff_path.write_text(
            f"# Auto-Handoff — {session_name}\n"
            f"*Generated by Ollama (Claude Code usage limit reached)*\n"
            f"*{datetime.now().strftime('%Y-%m-%d %H:%M')}*\n\n"
            f"> **Original task:** {task[:200]}\n\n"
            f"{response_text}\n"
        )
        log.info(f"Handoff written: {handoff_path}")
        return str(handoff_path)
    except TimeoutError:
        log.error("Ollama handoff timed out after 120s")
        return ""
    except OSError:
        log.error("Ollama not found — is it installed?")
        return ""


# Hard safety kill for a direct task's agent subprocess. Real work finishes in
# minutes; this only backstops a hung/looping agent so it can't run forever.
# ponytail: single fixed ceiling — make it per-task config if tasks ever vary wildly.
DIRECT_SAFETY_TIMEOUT_S = 7200  # 2h

# Live direct tasks, so `status` can show them and `abort` can kill them.
# session_name -> {"task", "project", "started", "proc"}
_DIRECT_TASKS: dict = {}
_DIRECT_LOCK = threading.Lock()


def _resolve_claude_bin() -> str:
    """Absolute path to the claude CLI — a launchd daemon's PATH can be minimal."""
    return shutil.which("claude") or str(Path.home() / ".local" / "bin" / "claude")


def run_task(
    task: str,
    session_name: Optional[str] = None,
    on_complete: Optional[Callable[[str], None]] = None,
    project: Optional[str] = None,
    cwd: Optional[str] = None,
) -> str:
    """Run a direct task via `claude --print` in a background thread.

    Returns immediately with a short ack. When the agent process exits (or is
    killed after DIRECT_SAFETY_TIMEOUT_S) the captured output is handed to
    on_complete — so the daemon never blocks and a slow task is never falsely
    reported as timed out. `cwd` (a project repo) is where the agent runs;
    `project` is echoed in the ack so a wrong route is visible immediately.
    """
    if not session_name:
        session_name = f"hermes-{int(time.time())}"

    log.info(f"Spawning direct task: {session_name}")
    log.info(f"Task: {task[:120]}...")

    task_file = Path.home() / "hermes" / "tasks" / f"{session_name}.md"
    task_file.parent.mkdir(parents=True, exist_ok=True)
    task_file.write_text(f"# Hermes Task\n\n{task}\n")
    log_file = Path.home() / "hermes" / "logs" / f"{session_name}.log"
    log_file.parent.mkdir(parents=True, exist_ok=True)

    # Direct tasks default to sonnet — the classifier sometimes routes real work
    # here, and the cheapest model bounces on anything non-trivial.
    try:
        direct_cfg = load_config().get("models", {}).get("agent_models", {}).get("direct", {})
    except Exception:
        direct_cfg = {}
    direct_model = direct_cfg.get("model", "sonnet")
    direct_max_turns = int(direct_cfg.get("max_turns", 30))

    cmd = [
        _resolve_claude_bin(),
        "--print",
        f"{project_map_text()}\n\n---\n\n{task}",
        "--model",
        str(direct_model),
        "--max-turns",
        str(direct_max_turns),
        # acceptEdits auto-approves file edits; --allowed-tools pre-approves the
        # read/inspect tools a phone status-check needs (ps, psql, git log, …) —
        # otherwise Bash is auto-denied in this headless run and "is X running?"
        # can't actually check anything.
        "--permission-mode",
        "acceptEdits",
        # Variadic — keep last so it collects all four tool names.
        "--allowed-tools",
        "Bash",
        "Read",
        "Grep",
        "Glob",
    ]

    run_cwd = str(Path(cwd).expanduser()) if cwd else str(Path.home())

    def _worker() -> None:
        result = ""
        try:
            proc = subprocess.Popen(
                cmd,
                cwd=run_cwd,
                stdout=subprocess.PIPE,
                stderr=subprocess.STDOUT,
                text=True,
            )
            with _DIRECT_LOCK:
                _DIRECT_TASKS[session_name] = {
                    "task": task,
                    "project": project,
                    "started": time.time(),
                    "proc": proc,
                }
            try:
                out, _ = proc.communicate(timeout=DIRECT_SAFETY_TIMEOUT_S)
                result = out.strip() or "(agent produced no output)"
                if proc.returncode and proc.returncode < 0:  # killed by a signal (abort)
                    result = f"🛑 Aborted.\n{result}"
            except subprocess.TimeoutExpired:
                proc.kill()
                out, _ = proc.communicate()
                hrs = DIRECT_SAFETY_TIMEOUT_S // 3600
                log.warning(f"Direct task hard-killed after {hrs}h: {session_name}")
                result = f"{(out or '').strip()}\n\n⚠️ Killed after {hrs}h safety timeout."
            log_file.write_text(result)
            log.info(f"Direct task complete: {session_name}")
        except Exception as exc:
            log.error(f"Direct task {session_name} failed: {exc}", exc_info=True)
            result = f"❌ Task {session_name} failed: {exc}"
        finally:
            with _DIRECT_LOCK:
                _DIRECT_TASKS.pop(session_name, None)

        if on_complete:
            try:
                on_complete(result)
            except Exception as exc:
                log.error(f"on_complete callback failed for {session_name}: {exc}")
        else:
            log.info(f"Direct task {session_name} result (no callback): {result[:200]}")

    threading.Thread(target=_worker, daemon=True, name=f"hermes-task-{session_name}").start()
    tag = f" (project: {project})" if project else ""
    return f"▶ Started {session_name}{tag} — I'll send the result when it's done."


# ---------------------------------------------------------------------------
# Pipeline orchestration helpers
# ---------------------------------------------------------------------------

RAPHBRAIN_DAILY_DIR = Path.home() / "Documents" / "RaphBrain" / "Daily"


def _append_pipeline_to_daily_note(
    project: str, branch: str, final_status: str, duration: str, failed_step: str = ""
) -> None:
    """Append a one-liner pipeline result to today's RaphBrain daily note."""
    try:
        today = datetime.now().strftime("%Y-%m-%d")
        daily_path = RAPHBRAIN_DAILY_DIR / f"{today}.md"

        if final_status == "done":
            line = f"\n- ✅ Hermes: `{project}/{branch}` done in {duration}"
        elif final_status == "failed":
            line = f"\n- ❌ Hermes: `{project}` failed at `{failed_step}` ({duration})"
        elif final_status == "aborted":
            line = f"\n- 🛑 Hermes: `{project}/{branch}` aborted ({duration})"
        else:
            return  # don't log unknown states

        if daily_path.exists():
            with daily_path.open("a") as f:
                f.write(line)
        else:
            daily_path.parent.mkdir(parents=True, exist_ok=True)
            daily_path.write_text(f"# {today}\n{line}\n")

        log.info(f"[daily-note] Appended pipeline result to {daily_path.name}")
    except Exception as exc:
        log.warning(f"[daily-note] Failed to write to daily note: {exc}")


def _format_duration(started_iso: str, ended_iso: str) -> str:
    """Return a human-readable duration like '2m 14s'."""
    try:
        fmt = "%Y-%m-%dT%H:%M:%SZ"
        delta = int(
            (
                datetime.strptime(ended_iso, fmt) - datetime.strptime(started_iso, fmt)
            ).total_seconds()
        )
        if delta < 0:
            delta = 0
        mins, secs = divmod(delta, 60)
        return f"{mins}m {secs:02d}s" if mins else f"{secs}s"
    except Exception:
        return "??"


def _send_imessage(reply_to: str, message: str) -> None:
    """Send an iMessage to reply_to (phone number or Apple ID) via osascript."""
    if not reply_to:
        log.info(f"[iMessage] (no reply_to configured): {message[:80]}")
        return
    safe = message.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    script = f"""tell application "Messages"
    set targetService to 1st service whose service type = iMessage
    set targetBuddy to buddy "{reply_to}" of targetService
    send "{safe}" to targetBuddy
end tell"""
    result = subprocess.run(["osascript", "-e", script], capture_output=True, text=True, timeout=10)
    if result.returncode != 0:
        log.error(f"iMessage send failed: {result.stderr.strip()}")
    else:
        log.info(f"iMessage sent to {reply_to}: {message[:80]}")


def _redact_token(text: str, token: Optional[str]) -> str:
    """Strip a bot token out of a string before it reaches the logs. requests
    exceptions embed the full request URL (…/bot<TOKEN>/…), so logging a raw exc
    leaks the token into hermes.log."""
    return text.replace(token, "***") if token else text


def _send_telegram(token: str, chat_id: int, message: str) -> None:
    """Send a message to a Telegram chat via Bot API."""
    try:
        resp = requests.post(
            f"https://api.telegram.org/bot{token}/sendMessage",
            json={"chat_id": chat_id, "text": message},
            timeout=10,
        )
        if not resp.ok:
            log.error(f"Telegram send failed: {_redact_token(resp.text, token)}")
        else:
            log.info(f"Telegram message sent to {chat_id}: {message[:80]}")
    except Exception as exc:
        log.error(f"Telegram send error: {_redact_token(str(exc), token)}")


def _send_reply(config: dict, message: str) -> None:
    """Send a reply via whichever channel is active (telegram or imessage)."""
    method = config.get("trigger", {}).get("method", "imessage")
    if method == "telegram":
        tcfg = config["trigger"]["telegram"]
        token = keyring.get_password(
            tcfg["bot_token_keychain_service"], tcfg["bot_token_keychain_account"]
        )
        _send_telegram(token, tcfg["chat_id"], message)
    else:
        reply_to = config.get("trigger", {}).get("imessage", {}).get("reply_to", "")
        _send_imessage(reply_to, message)


def _run_pipeline(run_id: str, engine: RunEngine, runner: AgentRunner, hermes_config: dict) -> None:
    """
    Background thread: drives a full pipeline run to completion.

    For each step (or parallel group of steps):
      1. Call AgentRunner.dispatch_step() -> task_id  (non-blocking)
      2. Call engine.mark_step_started(run_id, idx, task_id)
      3. Call engine.poll_step_completion()  (blocks until done/failed/timeout)
      4. Call engine.mark_step_done() or engine.mark_step_failed()
      5. Send milestone notification

    Parallel groups are dispatched as sub-threads and joined before continuing.
    Completion/failure notification is sent when the last step resolves.
    """

    def _dispatch_one_step(run_id: str, idx: int, step: dict, run_snapshot: dict) -> None:
        """Dispatch a single step, poll to completion, update engine state."""
        role = step["role"]
        try:
            task_id = runner.dispatch_step(
                step=step,
                run=run_snapshot,
                task_description=run_snapshot["task_raw"],
            )
        except Exception as exc:
            log.error(f"[orchestrate] dispatch_step failed for role={role}: {exc}")
            engine.mark_step_failed(run_id, idx, reason=f"dispatch failed: {exc}")
            return

        engine.mark_step_started(run_id, idx, task_id)
        log.info(f"[orchestrate] Step {idx} ({role}) dispatched as task {task_id}")

        final_status = engine.poll_step_completion(run_id, idx, task_id)

        if final_status in ("done", "needs-review"):
            if final_status == "needs-review":
                log.warning(f"[orchestrate] Step {idx} ({role}) needs-review — treating as done")
            output_path = engine._read_task_output_note(task_id)

            # Validate output note schema before advancing the pipeline.
            if output_path:
                valid, reason = validate_step_output(role, output_path)
                if not valid:
                    log.error(
                        f"[orchestrate] Schema validation failed step {idx} ({role}): {reason}"
                    )
                    engine.mark_step_failed(
                        run_id, idx, reason=f"Output schema validation failed: {reason}"
                    )
                    _send_reply(
                        hermes_config,
                        f"⚠️ Schema validation failed for {role}: {reason}",
                    )
                    return

            pr_url = None
            if role == "deployer" and output_path:
                pr_url = engine._extract_pr_url(output_path)
            engine.mark_step_done(run_id, idx, output_path=output_path, pr_url=pr_url)

            # Milestone notification
            try:
                run_now = engine.get_run(run_id)
                step_now = run_now["pipeline"][idx]
                started = step_now.get("started_at", "")
                completed = step_now.get("completed_at", "")
                duration = _format_duration(started, completed) if started and completed else "??"
                pipeline = run_now["pipeline"]
                next_roles = [
                    s["role"] for s in pipeline[idx + 1 :] if s.get("status") == "pending"
                ]
                next_label = next_roles[0] if next_roles else "done"
                milestone_msg = (
                    f"✓ {role} done ({duration}) — {run_now['project']}\nNext: {next_label}"
                )
                _send_reply(hermes_config, milestone_msg)
            except Exception as exc:
                log.warning(f"[orchestrate] Failed to send milestone notification: {exc}")

        else:
            # Auto-retry once for transient failures (failed / timeout).
            # rate-limited is never retried — it requires waiting for quota reset.
            run_now = engine.get_run(run_id)
            retry_count = run_now["pipeline"][idx].get("retry_count", 0)
            if final_status in ("failed", "timeout") and retry_count < STEP_MAX_RETRIES:
                log.warning(
                    f"[orchestrate] Step {idx} ({role}) got {final_status!r} — "
                    f"retrying in {STEP_RETRY_DELAY_S}s (attempt {retry_count + 1}/{STEP_MAX_RETRIES})"
                )
                engine.reset_step_for_retry(run_id, idx)
                time.sleep(STEP_RETRY_DELAY_S)
                fresh_run = engine.get_run(run_id)
                _dispatch_one_step(run_id, idx, fresh_run["pipeline"][idx], fresh_run)
                return

            reason_map = {
                "failed": "Agent task reported failed",
                "rate-limited": "Claude Code rate-limited — retry manually after reset",
                "timeout": "Step exceeded hard timeout",
            }
            reason = reason_map.get(final_status, final_status)
            engine.mark_step_failed(run_id, idx, reason=reason)

            # On rate-limit: synthesize a handoff from the partial checkpoint via Ollama
            # so work isn't lost and Jaiden can resume cleanly when quota resets.
            handoff_path = ""
            if final_status == "rate-limited":
                try:
                    output_note = engine._read_task_output_note(task_id)
                    partial_output = ""
                    if output_note:
                        note_path = Path.home() / "Documents" / "RaphBrain" / output_note
                        if note_path.exists():
                            partial_output = note_path.read_text()
                    handoff_path = write_handoff_via_ollama(
                        task=run_snapshot.get("task_raw", ""),
                        session_name=task_id,
                        partial_output=partial_output,
                    )
                    # Mirror handoff to the project's agents/ folder so the next
                    # fresh agent (on a new run) finds it during its RaphBrain scan.
                    if handoff_path:
                        project = run_snapshot.get("project", "")
                        if project:
                            proj_cap = project.capitalize()
                            agents_dir = (
                                Path.home()
                                / "Documents"
                                / "RaphBrain"
                                / "Projects"
                                / proj_cap
                                / "agents"
                            )
                            agents_dir.mkdir(parents=True, exist_ok=True)
                            mirror = agents_dir / f"hermes-rate-limited-{task_id}.md"
                            mirror.write_text(Path(handoff_path).read_text())
                            log.info(f"[orchestrate] Handoff mirrored to: {mirror}")
                except Exception as exc:
                    log.warning(f"[orchestrate] Ollama handoff failed: {exc}")

            handoff_line = f"\nHandoff: {handoff_path}" if handoff_path else ""
            blocker_msg = (
                f"⚠️ Blocked on {role}: {reason}{handoff_line}\n\n"
                f"Reply with:\n"
                f"[HERMES] abort — abort the run"
            )
            _send_reply(hermes_config, blocker_msg)

    log.info(f"[orchestrate] Pipeline thread started for run {run_id}")
    try:
        while True:
            run = engine.get_run(run_id)
            if run["status"] in ("failed", "aborted", "done"):
                break

            pipeline = run["pipeline"]
            next_steps = engine._find_next_pending_steps(pipeline)

            if not next_steps:
                # No more pending steps — finalise the run
                any_failed = any(s["status"] == "failed" for s in pipeline)
                final_status = "failed" if any_failed else "done"
                engine._update_run_fields(
                    run_id,
                    {
                        "status": final_status,
                        "completed_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
                    },
                )
                log.info(f"[orchestrate] Run {run_id} complete — status={final_status}")
                break

            if len(next_steps) == 1:
                idx, step = next_steps[0]
                _dispatch_one_step(run_id, idx, step, run)
            else:
                # Parallel group — spawn sub-threads, wait for all
                log.info(
                    f"[orchestrate] Parallel group ({len(next_steps)} steps) for run {run_id}: "
                    f"{[s['role'] for _, s in next_steps]}"
                )
                threads = []
                for idx, step in next_steps:
                    t = threading.Thread(
                        target=_dispatch_one_step,
                        args=(run_id, idx, step, run),
                        daemon=True,
                        name=f"hermes-step-{run_id}-{idx}",
                    )
                    threads.append(t)
                    t.start()
                for t in threads:
                    t.join()
                log.info(f"[orchestrate] Parallel group finished for run {run_id}")

    except Exception as exc:
        log.error(
            f"[orchestrate] Pipeline thread crashed for run {run_id}: {exc}",
            exc_info=True,
        )
        try:
            engine._update_run_fields(
                run_id,
                {
                    "status": "failed",
                    "completed_at": datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
                },
            )
        except Exception:
            pass
        _send_reply(hermes_config, f"❌ Pipeline thread crashed for run {run_id}. Check logs.")
        return

    # Send completion notification
    try:
        run = engine.get_run(run_id)
        project = run["project"]
        branch = run.get("branch", "")
        pr_url = run.get("pr_url")
        pipeline = run["pipeline"]
        done_count = sum(1 for s in pipeline if s["status"] == "done")
        step_count = len(pipeline)
        started_at = run.get("created_at", "")
        completed_at = run.get("completed_at", datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"))
        total_duration = _format_duration(started_at, completed_at) if started_at else "??"
        final_status = run["status"]

        if final_status == "done":
            if pr_url:
                completion_msg = (
                    f"✅ {project} — done\n"
                    f"PR: {pr_url}\n"
                    f"Duration: {total_duration}\n"
                    f"Steps: {done_count}/{step_count}"
                )
            else:
                completion_msg = (
                    f"✅ {project} — pipeline complete\n"
                    f"Duration: {total_duration}\n"
                    f"Steps: {done_count}/{step_count}"
                )
        elif final_status == "failed":
            failed_step = next((s["role"] for s in pipeline if s["status"] == "failed"), "unknown")
            completion_msg = f"❌ {project} failed at step {failed_step}. Check logs."
        elif final_status == "aborted":
            completion_msg = (
                f"\U0001f6d1 Run aborted: {project} / {branch}\n"
                f"Steps completed before abort: {done_count}/{step_count}"
            )
        else:
            completion_msg = f"\U0001f3c1 {project} run ended with status: {final_status}"

        _send_reply(hermes_config, completion_msg)

        # Append a one-liner to today's RaphBrain daily note.
        failed_step = ""
        if final_status == "failed":
            failed_step = next((s["role"] for s in pipeline if s["status"] == "failed"), "unknown")
        _append_pipeline_to_daily_note(project, branch, final_status, total_duration, failed_step)
    except Exception as exc:
        log.error(f"[orchestrate] Failed to send completion notification: {exc}")


def _direct_tasks_summary() -> str:
    """One line per live direct task, or '' if none."""
    with _DIRECT_LOCK:
        items = list(_DIRECT_TASKS.items())
    lines = []
    for name, info in items:
        elapsed = int(time.time() - info["started"])
        proj = info.get("project") or "—"
        lines.append(
            f"⚙️ {name} (project: {proj}) · {elapsed // 60}m{elapsed % 60:02d}s · {info['task'][:50]}"
        )
    return "\n".join(lines)


def _abort_direct_tasks() -> int:
    """Kill all live direct-task subprocesses. Returns how many were killed."""
    with _DIRECT_LOCK:
        procs = [(n, i["proc"]) for n, i in _DIRECT_TASKS.items()]
    for name, proc in procs:
        try:
            proc.kill()
            log.info(f"[abort] Killed direct task {name}")
        except Exception as exc:
            log.warning(f"[abort] Failed to kill {name}: {exc}")
    return len(procs)


def orchestrate_task(task_text: str, config: dict) -> str:
    """
    Route an incoming task through the planner.

    Both paths return a start-confirmation string immediately and report the
    real result later on their own channel:
    - Direct tasks: run_task() runs the agent in a background thread and sends
      the result via on_complete when the process exits.
    - Pipeline tasks: create a run file, start the engine in a daemon thread.

    config is the loaded config.yaml dict — needed for notification channel.
    """
    # Abort shortcut — intercept before planner so a rate-limited/stuck run
    # can always be cancelled without spinning up another pipeline.
    if task_text.strip().lower().startswith("abort"):
        killed = _abort_direct_tasks()
        engine = RunEngine()
        active = engine.get_active_run()
        msgs = []
        if killed:
            msgs.append(f"🛑 Killed {killed} direct task(s).")
        if active:
            try:
                engine.abort_run(active["id"])
                msgs.append(
                    f"🛑 Aborted run {active['id']} — "
                    f"{active.get('project', 'unknown')} / {active.get('branch', '')}"
                )
            except Exception as exc:
                log.warning(f"[orchestrate] abort_run failed: {exc}")
                msgs.append(f"⚠️ Abort failed: {exc}")
        return "\n".join(msgs) if msgs else "ℹ️ Nothing active to abort."

    # Status shortcut — fast local read of run state. Must intercept before the
    # planner, else "status" classifies as a direct task and spawns a 30-min
    # Claude session that blocks the whole poll loop.
    if task_text.strip().lower().rstrip("?") in (
        "status",
        "what's the status",
        "whats the status",
        "hermes status",
    ):
        engine = RunEngine()
        active = engine.get_active_run()
        direct = _direct_tasks_summary()
        if active:
            steps = active.get("pipeline", [])
            done = sum(1 for s in steps if s.get("status") == "done")
            cur = next(
                (s["role"] for s in steps if s.get("status") == "running"),
                next((s["role"] for s in steps if s.get("status") == "pending"), "—"),
            )
            started = active.get("created_at") or ""
            now = datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ")
            elapsed = _format_duration(started, now) if started else "?"
            pipeline_status = (
                f"🟢 {active.get('project', '?')} [Tier {active.get('tier', '?')}] "
                f"run {active['id']}\n"
                f"Step: {cur} ({done}/{len(steps)} done) · {elapsed}\n"
                f"Branch: {active.get('branch', '')}"
            )
        else:
            recent = engine.list_runs(limit=1)
            if recent:
                r = recent[0]
                pipeline_status = (
                    f"⚪️ No active pipeline run.\n"
                    f"Last: {r.get('project', '?')} run {r.get('id', '?')} → {r.get('status', '?')}"
                )
            else:
                pipeline_status = "⚪️ No active pipeline run."
        return f"{pipeline_status}\n\n{direct}".rstrip() if direct else pipeline_status

    # Discovery commands — help Jaiden drive from a phone without remembering the grammar.
    _cmd = task_text.strip().lower().rstrip("?")
    if _cmd in ("projects", "list projects"):
        return "Known projects:\n" + "\n".join(f"• {n}" for n in project_names())
    if _cmd in ("help", "commands", "menu"):
        return (
            "Hermes commands:\n"
            "• on <project>, <task> — run in a project (e.g. `on alphabot, fix the rebalance bug`)\n"
            "• <task> — I'll infer the project\n"
            "• status — current run\n"
            "• abort — cancel the active run\n"
            "• projects — list known projects"
        )

    result: PlannerResult = classify_task(task_text)
    log.info(
        f"[orchestrate] Classified: tier={result.tier} project={result.project!r} "
        f"is_direct={result.is_direct} steps={len(result.pipeline)}"
    )

    # Scaffold task — create project skeleton, return result synchronously
    if result.scaffold_project:
        log.info(f"[orchestrate] Scaffold task — project={result.scaffold_project!r}")
        return run_scaffold(result.scaffold_project)

    # Direct task — runs in the background; result is sent back on completion.
    if result.is_direct:
        log.info("[orchestrate] Direct task — routing to run_task()")
        proj = resolve_project(result.project)
        return run_task(
            task_text,
            on_complete=lambda r: _send_reply(config, r[:4096]),
            project=result.project if proj else None,
            cwd=(proj.repo if (proj and proj.repo) else None),
        )

    # Pipeline task — fail loud on an unknown project rather than dispatching an
    # agent that would silently run in $HOME against nothing.
    proj = resolve_project(result.project)
    if not proj or not proj.repo:
        known = ", ".join(project_names())
        log.warning(f"[orchestrate] Refusing pipeline for unresolvable project {result.project!r}")
        return (
            f"❓ Couldn't map that to a project with a repo (got {result.project!r}).\n"
            f"Try prefixing it, e.g. `on arbiter, …`.\nKnown: {known}"
        )

    engine = RunEngine()
    runner = AgentRunner()

    try:
        run = engine.create_run(task_raw=task_text, result=result)
    except RuntimeError as exc:
        # Another run is already active — queue not yet supported
        log.warning(f"[orchestrate] create_run blocked: {exc}")
        return f"⚠️ {exc}\nSend [HERMES] abort to cancel the current run first."

    run_id = run["id"]
    pipeline_summary = " → ".join(s.role for s in result.pipeline)

    start_msg = (
        f"\U0001f4cb [Tier {result.tier}] {result.project} — {pipeline_summary}\n\n"
        f"Starting now. I'll ping you at each milestone.\n"
        f"Branch: {result.branch_name}"
    )

    # Set run to running before spawning the thread
    engine._update_run_field(run_id, "status", "running")

    t = threading.Thread(
        target=_run_pipeline,
        args=(run_id, engine, runner, config),
        daemon=True,
        name=f"hermes-pipeline-{run_id}",
    )
    t.start()
    log.info(f"[orchestrate] Pipeline thread started: run={run_id} project={result.project}")

    return start_msg


def notify(config: dict, subject: str, body: str):
    method = config["notification"]["method"]

    if method == "log_only":
        log.info(f"NOTIFY: {subject} | {body}")
        return

    if method == "email":
        cfg = config["notification"]["email"]
        try:
            password = keyring.get_password("hermes-gmail", "hermes")
            msg = MIMEText(body)
            msg["Subject"] = f"[Hermes] {subject}"
            msg["From"] = cfg["from"]
            msg["To"] = cfg["to"]

            with smtplib.SMTP(cfg["smtp_host"], cfg["smtp_port"]) as server:
                server.starttls()
                server.login(cfg["from"], password)
                server.send_message(msg)
            log.info(f"Notification sent: {subject}")
        except Exception as e:
            log.error(f"Failed to send notification: {e}")


class TelegramPoller:
    """
    Polls Telegram Bot API for new messages.
    Uses long-offset tracking in config/telegram_state.json to avoid reprocessing.
    Replies via sendMessage API.
    """

    STATE_FILE = Path.home() / "hermes" / "config" / "telegram_state.json"

    def __init__(self, config):
        self.cfg = config["trigger"]["telegram"]
        self.hermes_cfg = config
        self.chat_id = self.cfg["chat_id"]
        self.prefix = self.cfg.get("trigger_prefix", "[HERMES]")
        self.token = keyring.get_password(
            self.cfg["bot_token_keychain_service"],
            self.cfg["bot_token_keychain_account"],
        )
        self.offset = self._load_offset()
        log.info(f"Telegram poller ready — chat_id={self.chat_id} offset={self.offset}")

    def _load_offset(self) -> int:
        try:
            if self.STATE_FILE.exists():
                data = json.loads(self.STATE_FILE.read_text())
                return int(data.get("offset", 0))
        except Exception:
            pass
        return 0

    def _save_offset(self, offset: int):
        self.STATE_FILE.write_text(json.dumps({"offset": offset}))

    def poll(self):
        try:
            # Long-poll: getUpdates blocks up to 25s and returns the moment a message
            # arrives — near-instant pickup, far fewer requests than short-poll + sleep.
            resp = requests.get(
                f"https://api.telegram.org/bot{self.token}/getUpdates",
                params={"offset": self.offset, "timeout": 25},
                timeout=30,
            )
            if not resp.ok:
                log.error(f"Telegram getUpdates failed: {_redact_token(resp.text, self.token)}")
                return

            updates = resp.json().get("result", [])
            for update in updates:
                self.offset = update["update_id"] + 1
                self._save_offset(self.offset)

                msg = update.get("message", {})
                if not msg or msg.get("chat", {}).get("id") != self.chat_id:
                    continue

                text = msg.get("text", "").strip()
                if not text:
                    continue

                task = text[len(self.prefix) :].strip() if text.startswith(self.prefix) else text
                self._journal(update["update_id"], task)
                log.info(f"Telegram task: {task[:80]}...")
                # Process off the poll loop: a slow classification (Ollama ~15-30s)
                # must not freeze pickup of the next message. Ack immediately.
                self._reply("👀 on it")
                threading.Thread(
                    target=self._process, args=(task,), daemon=True, name="hermes-tg-task"
                ).start()

        except Exception as exc:
            log.error(f"Telegram poll error: {_redact_token(str(exc), self.token)}")

    def _process(self, task: str):
        try:
            reply = orchestrate_task(task, self.hermes_cfg)
            self._reply(reply[:4096])
        except Exception as task_exc:
            log.error(f"Task execution error: {task_exc}", exc_info=True)
            self._reply(f"❌ Error: {task_exc}")

    def _journal(self, update_id: int, task: str):
        """Append the raw message before processing so a daemon crash mid-task
        leaves a trace instead of silently losing it (offset already advanced)."""
        try:
            jpath = Path.home() / "hermes" / "logs" / "telegram-journal.log"
            with jpath.open("a") as f:
                f.write(f"{update_id}\t{task}\n")
        except Exception:
            pass

    def _reply(self, message: str):
        _send_telegram(self.token, self.chat_id, message)


class iMessagePoller:
    """
    Polls Messages.app via osascript — no Full Disk Access required.
    Tracks last-checked timestamp in config/imessage_state.json.
    Replies via osascript -> Messages.app.
    """

    STATE_FILE = Path.home() / "hermes" / "config" / "imessage_state.json"

    def __init__(self, config):
        self.cfg = config["trigger"]["imessage"]
        self.reply_to = self.cfg.get("reply_to", "")
        self.prefix = self.cfg.get("trigger_prefix", "[HERMES]")
        self.hermes_cfg = config
        self.last_check = self._load_last_check()
        log.info(
            f"iMessage poller ready (osascript, no FDA) — "
            f"tracking from {self.last_check:%Y-%m-%d %H:%M:%S}"
        )

    def _load_last_check(self) -> datetime:
        try:
            if self.STATE_FILE.exists():
                data = json.loads(self.STATE_FILE.read_text())
                ts = data.get("last_check_ts")
                if ts:
                    return datetime.fromtimestamp(float(ts))
        except Exception:
            pass
        # First run: start from now so we don't replay old messages
        now = datetime.now()
        self._save_last_check(now)
        return now

    def _save_last_check(self, dt: datetime):
        self.STATE_FILE.write_text(json.dumps({"last_check_ts": dt.timestamp()}))

    def poll(self):
        now = datetime.now()
        # macOS AppleScript date string — no zero-padded day or hour
        cutoff_str = self.last_check.strftime("%B %-d, %Y at %-I:%M:%S %p")
        prefix_esc = self.prefix.replace('"', '\\"')

        script = f"""set cutoff to date "{cutoff_str}"
set triggerPrefix to "{prefix_esc}"
set output to ""
tell application "Messages"
    repeat with aChat in chats
        try
            set msgs to messages of aChat
            set msgCount to count of msgs
            set startIdx to msgCount - 19
            if startIdx < 1 then set startIdx to 1
            repeat with i from startIdx to msgCount
                set aMsg to item i of msgs
                try
                    if (date sent of aMsg) > cutoff then
                        set msgText to text of aMsg
                        if msgText starts with triggerPrefix then
                            set output to output & msgText & "|||HSEP|||"
                        end if
                    end if
                end try
            end repeat
        end try
    end repeat
end tell
return output"""

        result = subprocess.run(
            ["osascript", "-e", script], capture_output=True, text=True, timeout=30
        )

        self.last_check = now
        self._save_last_check(now)

        if result.returncode != 0:
            log.error(f"osascript poll error: {result.stderr.strip()}")
            return

        output = result.stdout.strip()
        if not output:
            return

        tasks = [m.strip() for m in output.split("|||HSEP|||") if m.strip()]
        for text in tasks:
            task = text[len(self.prefix) :].strip()
            log.info(f"iMessage task: {task[:80]}...")
            reply = orchestrate_task(task, self.hermes_cfg)
            self._reply(reply[:1500])

    def _reply(self, message: str):
        if not self.reply_to:
            log.info(f"[no reply_to configured] RESULT: {message}")
            return

        safe = message.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
        script = f"""tell application "Messages"
    set targetService to 1st service whose service type = iMessage
    set targetBuddy to buddy "{self.reply_to}" of targetService
    send "{safe}" to targetBuddy
end tell"""

        result = subprocess.run(
            ["osascript", "-e", script], capture_output=True, text=True, timeout=10
        )
        if result.returncode != 0:
            log.error(f"iMessage reply failed: {result.stderr.strip()}")
        else:
            log.info(f"Reply sent via iMessage to {self.reply_to}")


class EmailPoller:
    def __init__(self, config):
        self.cfg = config["trigger"]["email"]
        self.hermes_cfg = config

    def poll(self):
        try:
            password = keyring.get_password(
                self.cfg["password_keychain_service"],
                self.cfg["password_keychain_account"],
            )
            mail = imaplib.IMAP4_SSL(self.cfg["imap_host"], self.cfg["imap_port"])
            mail.login(self.cfg["username"], password)
            mail.select("inbox")

            prefix = self.cfg["trigger_subject_prefix"]
            _, msgs = mail.search(None, f'(UNSEEN SUBJECT "{prefix}")')

            for num in msgs[0].split():
                _, data = mail.fetch(num, "(RFC822)")
                msg = email.message_from_bytes(data[0][1])
                subject = msg["subject"]
                task = subject.replace(prefix, "").strip()

                if msg.is_multipart():
                    for part in msg.walk():
                        if part.get_content_type() == "text/plain":
                            task += "\n\n" + part.get_payload(decode=True).decode()
                            break
                else:
                    task += "\n\n" + msg.get_payload(decode=True).decode()

                log.info(f"Received task via email: {task[:80]}...")
                mail.store(num, "+FLAGS", "\\Seen")

                run_task(
                    task,
                    on_complete=lambda r: notify(self.hermes_cfg, "Task complete", r[:2000]),
                )

            mail.logout()
        except Exception as e:
            log.error(f"Email poll error: {e}")


class FileWatcher(FileSystemEventHandler):
    def __init__(self, config):
        self.hermes_cfg = config

    def on_created(self, event):
        if event.is_directory or not event.src_path.endswith(".task"):
            return
        path = Path(event.src_path)
        log.info(f"Task file detected: {path.name}")
        task = path.read_text().strip()
        run_task(
            task,
            session_name=path.stem,
            on_complete=lambda r: notify(self.hermes_cfg, f"Task complete: {path.stem}", r[:2000]),
        )
        path.unlink()


class WebhookListener:
    def __init__(self, config):
        self.cfg = config["trigger"]["webhook"]
        self.hermes_cfg = config

    def run(self):
        from http.server import HTTPServer, BaseHTTPRequestHandler
        import hmac
        import hashlib

        secret = self.cfg["secret"].encode()
        hermes_cfg = self.hermes_cfg

        class Handler(BaseHTTPRequestHandler):
            def do_POST(self):
                length = int(self.headers.get("Content-Length", 0))
                body = self.rfile.read(length)
                sig = self.headers.get("X-Hermes-Signature", "")

                expected = hmac.new(secret, body, hashlib.sha256).hexdigest()
                if not hmac.compare_digest(sig, expected):
                    self.send_response(403)
                    self.end_headers()
                    return

                data = json.loads(body)
                task = data.get("task", "")
                log.info(f"Webhook task received: {task[:80]}...")

                self.send_response(202)
                self.end_headers()
                self.wfile.write(b'{"status": "accepted"}')

                run_task(
                    task,
                    on_complete=lambda r: notify(hermes_cfg, "Task complete", r[:2000]),
                )

            def log_message(self, *args):
                pass

        server = HTTPServer((self.cfg["host"], self.cfg["port"]), Handler)
        log.info(f"Webhook listener on port {self.cfg['port']}")
        server.serve_forever()


def main():
    log.info("=== Hermes starting up ===")
    config = load_config()
    method = config["trigger"]["method"]

    subprocess.run([str(Path.home() / "hermes" / "scripts" / "check-connectivity.sh")])

    # Recover crash-orphaned runs ONCE here — never per-message (see RunEngine).
    RunEngine().startup_recover_and_cleanup()

    if method == "telegram":
        log.info("Trigger: Telegram polling")
        poller = TelegramPoller(config)
        while True:
            poller.poll()
            time.sleep(1)  # poll() long-polls up to 25s; this is just a loop breather

    elif method == "imessage":
        log.info("Trigger: iMessage polling")
        poller = iMessagePoller(config)
        while True:
            poller.poll()
            time.sleep(config["trigger"]["imessage"]["poll_interval_seconds"])

    elif method == "email":
        log.info("Trigger: email polling")
        poller = EmailPoller(config)
        while True:
            poller.poll()
            time.sleep(config["trigger"]["email"]["poll_interval_seconds"])

    elif method == "file_watch":
        log.info(f"Trigger: file watch on {config['trigger']['file_watch']['watch_dir']}")
        observer = Observer()
        handler = FileWatcher(config)
        observer.schedule(handler, config["trigger"]["file_watch"]["watch_dir"], recursive=False)
        observer.start()
        try:
            while True:
                time.sleep(1)
        except KeyboardInterrupt:
            observer.stop()
        observer.join()

    elif method == "webhook":
        log.info("Trigger: webhook")
        WebhookListener(config).run()


if __name__ == "__main__":
    main()
